// Story Campaign Stages and Difficulty Tiers

export const DIFFICULTY_TIERS = {
  rookie: {
    id: 'rookie',
    name: 'Rookie / Kid Mode',
    icon: '🐣',
    startElo: 50,
    desc: 'Starts at 50 ELO with +25/+50 ELO step increments. Full Pikachu Helper Coach hints & Unlimited Undos.',
  },
  trainer: {
    id: 'trainer',
    name: 'Trainer Mode',
    icon: '🧢',
    startElo: 300,
    desc: 'Starts at 300 ELO with +50 ELO step increments. Standard move dots enabled.',
  },
  champion: {
    id: 'champion',
    name: 'Master / Champion Mode',
    icon: '👑',
    startElo: 1000,
    desc: 'Starts at 1000 ELO up to 2400 ELO Red. Hints locked off, deep AI search.',
  },
};

export const STORY_STAGES = [
  {
    id: 1,
    name: 'Baby Pichu',
    trainerTitle: 'Pichu Nest',
    elo: 50,
    tier: 'rookie',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/172.png',
    dialogue: 'Pi-pi-pichu! Let\'s play a super easy game of Pokémon Chess!',
    theme: 'petalburg',
    badge: { id: 'rookie_ribbon', name: 'Rookie Ribbon', icon: '🏅' },
    hasCoach: true,
  },
  {
    id: 2,
    name: 'Rookie Timmy',
    trainerTitle: 'Novice Trainer',
    elo: 100,
    tier: 'rookie',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/youngster-gen4.png',
    dialogue: 'I just learned how to move my pawns forward!',
    theme: 'petalburg',
    badge: null,
    hasCoach: true,
  },
  {
    id: 3,
    name: 'Youngster Tristan',
    trainerTitle: 'Route 101 Trainer',
    elo: 150,
    tier: 'rookie',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/youngster.png',
    dialogue: 'My Rattata is in the top percentage of Rattatas!',
    theme: 'petalburg',
    badge: null,
    hasCoach: true,
  },
  {
    id: 4,
    name: 'Bug Catcher Joey',
    trainerTitle: 'Viridian Forest',
    elo: 200,
    tier: 'rookie',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/bugcatcher.png',
    dialogue: 'Watch out! My Caterpie piece will march down the board!',
    theme: 'petalburg',
    badge: { id: 'bug_badge', name: 'Insect Ribbon', icon: '🐛' },
    hasCoach: true,
  },
  {
    id: 5,
    name: 'Fisherman Ned',
    trainerTitle: 'Route 102 Fisherman',
    elo: 250,
    tier: 'rookie',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/fisherman.png',
    dialogue: 'Patience is key! My Magikarp piece will splash to victory!',
    theme: 'sootopolis',
    badge: null,
    hasCoach: true,
  },
  {
    id: 6,
    name: 'Lass Carrie',
    trainerTitle: 'Petalburg Woods',
    elo: 300,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/lass.png',
    dialogue: 'I always develop my Knights and Bishops before attacking!',
    theme: 'petalburg',
    badge: null,
    hasCoach: true,
  },
  {
    id: 7,
    name: 'Camper Liam',
    trainerTitle: 'Route 104 Camper',
    elo: 350,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/camper.png',
    dialogue: 'Camping out here taught me how to guard open squares!',
    theme: 'petalburg',
    badge: null,
    hasCoach: true,
  },
  {
    id: 8,
    name: 'Picnicker Diane',
    trainerTitle: 'Petalburg Outskirts',
    elo: 400,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/picnicker.png',
    dialogue: 'I won\'t let you capture my pieces easily!',
    theme: 'petalburg',
    badge: { id: 'forest_badge', name: 'Forest Ribbon', icon: '🌲' },
    hasCoach: true,
  },
  {
    id: 9,
    name: 'Hiker Anthony',
    trainerTitle: 'Mt. Chimney Foothills',
    elo: 450,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/hiker.png',
    dialogue: 'My defense is as solid as Geodude!',
    theme: 'volcano',
    badge: null,
    hasCoach: true,
  },
  {
    id: 10,
    name: 'Black Belt Kiyo',
    trainerTitle: 'Dewford Dojo',
    elo: 500,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/blackbelt.png',
    dialogue: 'Control the center of the board with raw martial discipline!',
    theme: 'skypillar',
    badge: { id: 'fight_badge', name: 'Knuckle Badge', icon: '🥊' },
    hasCoach: true,
  },
  {
    id: 11,
    name: 'Psychic Edward',
    trainerTitle: 'Mauville Psychic',
    elo: 550,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/psychic.png',
    dialogue: 'I foresee your moves before you even make them!',
    theme: 'mauville',
    badge: null,
    hasCoach: false,
  },
  {
    id: 12,
    name: 'Kindler Mark',
    trainerTitle: 'Mt. Chimney Summit',
    elo: 600,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/kindler.png',
    dialogue: 'Burn through enemy lines with fierce attacks!',
    theme: 'volcano',
    badge: { id: 'heat_badge', name: 'Heat Badge', icon: '🔥' },
    hasCoach: false,
  },
  {
    id: 13,
    name: 'Bird Keeper Toby',
    trainerTitle: 'Fortree Canopy',
    elo: 650,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/birdkeeper.png',
    dialogue: 'Castle early and soar over enemy defenses!',
    theme: 'skypillar',
    badge: null,
    hasCoach: false,
  },
  {
    id: 14,
    name: 'Rocker Hank',
    trainerTitle: 'New Mauville Plant',
    elo: 700,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/guitarist.png',
    dialogue: 'Electrify the board with high-voltage tactical checks!',
    theme: 'mauville',
    badge: null,
    hasCoach: false,
  },
  {
    id: 15,
    name: 'Leader Brock',
    trainerTitle: 'Pewter City Gym',
    elo: 750,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/brock.png',
    dialogue: 'My Onix piece will form an unshakeable rock wall!',
    theme: 'classic',
    badge: { id: 'boulder_badge', name: 'Boulder Badge', icon: '🪨' },
    hasCoach: false,
  },
  {
    id: 16,
    name: 'Leader Misty',
    trainerTitle: 'Cerulean City Gym',
    elo: 800,
    tier: 'trainer',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/misty.png',
    dialogue: 'My Starmie piece will sweep your back rank!',
    theme: 'sootopolis',
    badge: { id: 'cascade_badge', name: 'Cascade Badge', icon: '💧' },
    hasCoach: false,
  },
  {
    id: 17,
    name: 'Gym Leader Wattson',
    trainerTitle: 'Mauville Gym Leader',
    elo: 1000,
    tier: 'champion',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/wattson.png',
    dialogue: 'Bwahaha! Electric tactics will spark your defeat!',
    theme: 'mauville',
    badge: { id: 'dynamo_badge', name: 'Dynamo Badge', icon: '⚡' },
    hasCoach: false,
  },
  {
    id: 18,
    name: 'Gym Leader Wallace',
    trainerTitle: 'Sootopolis Gym Leader',
    elo: 1300,
    tier: 'champion',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/wallace.png',
    dialogue: 'Allow me to show you the true elegance of Pokémon Chess!',
    theme: 'sootopolis',
    badge: { id: 'rain_badge', name: 'Rain Badge', icon: '🌧️' },
    hasCoach: false,
  },
  {
    id: 19,
    name: 'Elite Four Lance',
    trainerTitle: 'Indigo League Champion',
    elo: 1600,
    tier: 'champion',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/lance.png',
    dialogue: 'Dragon Pokémon know no equal in tactical power!',
    theme: 'classic',
    badge: { id: 'dragon_badge', name: 'Dragon Trophy', icon: '🐉' },
    hasCoach: false,
  },
  {
    id: 20,
    name: 'Champion Cynthia',
    trainerTitle: 'Sinnoh League Champion',
    elo: 2000,
    tier: 'champion',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/cynthia.png',
    dialogue: 'I have analyzed every variation. Show me your true strength!',
    theme: 'skypillar',
    badge: { id: 'champion_trophy', name: 'Champion Trophy', icon: '🏆' },
    hasCoach: false,
  },
  {
    id: 21,
    name: 'Legend Red',
    trainerTitle: 'Mt. Silver Peak',
    elo: 2400,
    tier: 'champion',
    iconUrl: 'https://play.pokemonshowdown.com/sprites/trainers/red.png',
    dialogue: '...',
    theme: 'ice',
    badge: { id: 'legend_star', name: 'Legend Star', icon: '⭐' },
    hasCoach: false,
  },
];
