export const ARENA_THEMES = [
  {
    id: 'classic',
    name: 'Indigo Plateau',
    icon: '👑',
    region: 'Gen 1 Kanto',
    desc: 'Official Pokemon League Championship Arena',
    bg: 'radial-gradient(circle at top center, #1e293b 0%, #0f172a 100%)',
    boardBorder: '#334155',
    squareLight: '#e2e8f0',
    squareDark: '#64748b',
    accent: '#f59e0b',
  },
  {
    id: 'volcano',
    name: 'Mt. Chimney',
    icon: '🌋',
    region: 'Gen 3 Hoenn',
    desc: 'Volcanic magma peak & molten obsidian squares',
    bg: 'radial-gradient(circle at top center, #450a0a 0%, #1a0505 50%, #080202 100%)',
    boardBorder: '#dc2626',
    squareLight: '#ffedd5',
    squareDark: '#991b1b',
    accent: '#f97316',
  },
  {
    id: 'ice',
    name: 'Shoal Cave',
    icon: '❄️',
    region: 'Gen 3 Hoenn',
    desc: 'Glacial ice cavern & crystalline cyan squares',
    bg: 'radial-gradient(circle at top center, #0c4a6e 0%, #082f49 50%, #031726 100%)',
    boardBorder: '#38bdf8',
    squareLight: '#e0f2fe',
    squareDark: '#0284c7',
    accent: '#38bdf8',
  },
  {
    id: 'petalburg',
    name: 'Petalburg Woods',
    icon: '🌲',
    region: 'Gen 3 Hoenn',
    desc: 'Ancient forest canopy & mossy timber squares',
    bg: 'radial-gradient(circle at top center, #064e3b 0%, #022c22 50%, #011910 100%)',
    boardBorder: '#22c55e',
    squareLight: '#dcfce7',
    squareDark: '#15803d',
    accent: '#4ade80',
  },
  {
    id: 'sootopolis',
    name: 'Sootopolis City',
    icon: '🌊',
    region: 'Gen 3 Hoenn',
    desc: 'Sacred volcanic crater lake & deep ocean sapphire',
    bg: 'radial-gradient(circle at top center, #172554 0%, #1e3a8a 50%, #0f172a 100%)',
    boardBorder: '#2563eb',
    squareLight: '#dbeafe',
    squareDark: '#1d4ed8',
    accent: '#60a5fa',
  },
  {
    id: 'skypillar',
    name: 'Sky Pillar',
    icon: '🌌',
    region: 'Gen 3 Hoenn',
    desc: "Rayquaza's ancient high-sky Rayquaza shrine",
    bg: 'radial-gradient(circle at top center, #022c22 0%, #064e3b 50%, #021f18 100%)',
    boardBorder: '#10b981',
    squareLight: '#ecfdf5',
    squareDark: '#047857',
    accent: '#34d399',
  },
  {
    id: 'mauville',
    name: 'New Mauville',
    icon: '⚡',
    region: 'Gen 3 Hoenn',
    desc: 'High-tech underground generator plant',
    bg: 'radial-gradient(circle at top center, #422006 0%, #1c1917 50%, #0c0a09 100%)',
    boardBorder: '#eab308',
    squareLight: '#fef9c3',
    squareDark: '#ca8a04',
    accent: '#facc15',
  },
  {
    id: 'pyre',
    name: 'Mt. Pyre',
    icon: '🔮',
    region: 'Gen 3 Hoenn',
    desc: 'Mist-shrouded sacred peak & spectral shadow squares',
    bg: 'radial-gradient(circle at top center, #3b0764 0%, #2e1065 50%, #17072b 100%)',
    boardBorder: '#a855f7',
    squareLight: '#f3e8ff',
    squareDark: '#7e22ce',
    accent: '#c084fc',
  },
];
