// Wild Pokémon Tactical Puzzle Encounters (Opening, Midgame, Endgame Puzzles)

export const WILD_POKEMON_PUZZLES = [
  {
    id: 'wild_pikachu',
    pokemonName: 'Pikachu',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    type: 'Opening',
    title: 'Pikachu\'s King Pawn Opening! ⚡',
    prompt: 'A Wild Pikachu appeared! Open the game by advancing your King Pawn 2 squares (e2 to e4) to control the center!',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    solutionMove: { from: 'e2', to: 'e4' },
    rewardText: 'Gotcha! Wild Pikachu was caught! ⚡',
    coachHint: 'Pikachu says: Move your pawn from e2 to e4 to claim the center of the board!',
  },
  {
    id: 'wild_charmander',
    pokemonName: 'Charmander',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    type: 'Midgame Tactical Fork',
    title: 'Charmander\'s Knight Fork! 🔥',
    prompt: 'A Wild Charmander is cornered! Move your Knight to c7 to fork Black\'s King and Rook at the same time!',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    solutionMove: { from: 'f3', to: 'e5' },
    rewardText: 'Gotcha! Wild Charmander was caught! 🔥',
    coachHint: 'Pikachu says: Take Black\'s pawn on e5 with your Knight to attack two pieces at once!',
  },
  {
    id: 'wild_squirtle',
    pokemonName: 'Squirtle',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    type: 'Endgame Checkmate',
    title: 'Squirtle\'s Back-Rank Checkmate! 💧',
    prompt: 'A Wild Squirtle wants to see your finisher! Move your Queen to h7 to deliver Checkmate in 1 move!',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 4 5',
    solutionMove: { from: 'c4', to: 'f7' },
    rewardText: 'Gotcha! Wild Squirtle was caught! 💧',
    coachHint: 'Pikachu says: Move your Bishop to f7 to checkmate the enemy King!',
  },
  {
    id: 'wild_eevee',
    pokemonName: 'Eevee',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    type: 'Endgame Pawn Promotion',
    title: 'Eevee\'s Pawn Evolution! ⭐',
    prompt: 'A Wild Eevee is watching! Push your Pawn from e7 to e8 to promote into a Queen!',
    fen: '4k3/4P3/8/8/8/8/8/4K3 w - - 0 1',
    solutionMove: { from: 'e7', to: 'e8' },
    rewardText: 'Gotcha! Wild Eevee was caught! ⭐',
    coachHint: 'Pikachu says: Move your Pawn all the way to the 8th rank to evolve into a Queen!',
  },
];
