// Environment-Mapped Wild Pokémon Tactical Quiz Encounters

export const WILD_POKEMON_PUZZLES = [
  // Petalburg Woods (Grass / Bug / Electric)
  {
    id: 'wild_pikachu',
    pokemonName: 'Pikachu',
    region: 'petalburg',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    type: 'Opening',
    title: 'Pikachu\'s King Pawn Opening! ⚡',
    prompt: 'A Wild Pikachu appeared in Petalburg Woods! Advance your King Pawn 2 squares (e2 to e4) to control the center!',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    solutionMove: { from: 'e2', to: 'e4' },
    rewardText: 'Gotcha! Wild Pikachu was caught! Registered in Petalburg Pokédex! ⚡',
    coachHint: 'Pikachu says: Move your pawn from e2 to e4 to claim the center of the board!',
  },
  {
    id: 'wild_treecko',
    pokemonName: 'Treecko',
    region: 'petalburg',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png',
    type: 'Knight Fork',
    title: 'Treecko\'s Tree Jump Fork! 🌿',
    prompt: 'A Wild Treecko is perched in the trees! Jump your Knight to c7 to fork Black\'s King and Rook!',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    solutionMove: { from: 'f3', to: 'e5' },
    rewardText: 'Gotcha! Wild Treecko was caught! Registered in Pokédex! 🌿',
    coachHint: 'Pikachu says: Take Black\'s pawn on e5 with your Knight to attack two pieces at once!',
  },

  // Mt. Chimney Volcano (Fire / Magma)
  {
    id: 'wild_charmander',
    pokemonName: 'Charmander',
    region: 'volcano',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    type: 'Fire Strike',
    title: 'Charmander\'s Volcanic Strike! 🔥',
    prompt: 'A Wild Charmander emerged from the magma crater! Strike with your Bishop on f7 to deliver Checkmate!',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 4 5',
    solutionMove: { from: 'c4', to: 'f7' },
    rewardText: 'Gotcha! Wild Charmander was caught! Registered in Volcano Pokédex! 🔥',
    coachHint: 'Pikachu says: Move your Bishop to f7 to checkmate the enemy King!',
  },
  {
    id: 'wild_slugma',
    pokemonName: 'Slugma',
    region: 'volcano',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/218.png',
    type: 'Center Defense',
    title: 'Slugma\'s Magma Barrier! 🌋',
    prompt: 'A Wild Slugma is blocking the trail! Advance your Queen Pawn to d4 to solidify center control!',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2',
    solutionMove: { from: 'd2', to: 'd4' },
    rewardText: 'Gotcha! Wild Slugma was caught! Registered in Volcano Pokédex! 🌋',
    coachHint: 'Pikachu says: Advance your d-pawn to d4 to control the middle!',
  },

  // Sootopolis Lake (Water)
  {
    id: 'wild_squirtle',
    pokemonName: 'Squirtle',
    region: 'sootopolis',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    type: 'Back-Rank Mate',
    title: 'Squirtle\'s Water Surf Checkmate! 💧',
    prompt: 'A Wild Squirtle emerged from Sootopolis Crater Lake! Surf your Rook along the back rank to deliver Checkmate!',
    fen: '6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
    solutionMove: { from: 'b1', to: 'b8' },
    rewardText: 'Gotcha! Wild Squirtle was caught! Registered in Sootopolis Pokédex! 💧',
    coachHint: 'Pikachu says: Move your Rook all the way to b8 for Back-Rank Checkmate!',
  },
  {
    id: 'wild_lotad',
    pokemonName: 'Lotad',
    region: 'sootopolis',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/270.png',
    type: 'Diagonal Skewer',
    title: 'Lotad\'s Water Lily Skewer! 🌊',
    prompt: 'A Wild Lotad is floating on the lily pads! Move your Bishop along the diagonal to c4!',
    fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1',
    solutionMove: { from: 'f1', to: 'c4' },
    rewardText: 'Gotcha! Wild Lotad was caught! Registered in Sootopolis Pokédex! 🌊',
    coachHint: 'Pikachu says: Move your Bishop from f1 to c4!',
  },

  // Mauville Plant (Electric / Steel)
  {
    id: 'wild_magnemite',
    pokemonName: 'Magnemite',
    region: 'mauville',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    type: 'Electric Pin',
    title: 'Magnemite\'s Magnetic Pin! ⚡',
    prompt: 'A Wild Magnemite is hovering near the power core! Pin Black\'s Knight by moving your Bishop to b5!',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    solutionMove: { from: 'f1', to: 'b5' },
    rewardText: 'Gotcha! Wild Magnemite was caught! Registered in Mauville Pokédex! ⚡',
    coachHint: 'Pikachu says: Move your Bishop from f1 to b5 to pin the Knight!',
  },

  // Shoal Ice Cave (Ice)
  {
    id: 'wild_snorunt',
    pokemonName: 'Snorunt',
    region: 'ice',
    type: 'Castling Safety',
    title: 'Snorunt\'s Frozen Castle! ❄️',
    prompt: 'A Wild Snorunt is shivering in Shoal Cave! Castle your King kingside (e1 to g1) to secure your King in an icy fortress!',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    solutionMove: { from: 'e1', to: 'g1' },
    rewardText: 'Gotcha! Wild Snorunt was caught! Registered in Ice Cave Pokédex! ❄️',
    coachHint: 'Pikachu says: Move your King 2 squares to g1 to castle and protect your King!',
  },

  // Indigo League (Normal / Evolution)
  {
    id: 'wild_eevee',
    pokemonName: 'Eevee',
    region: 'classic',
    iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    type: 'Pawn Evolution',
    title: 'Eevee\'s Queen Evolution! ⭐',
    prompt: 'A Wild Eevee is watching the League matches! Push your Pawn from e7 to e8 to evolve into a Queen!',
    fen: '4k3/4P3/8/8/8/8/8/4K3 w - - 0 1',
    solutionMove: { from: 'e7', to: 'e8' },
    rewardText: 'Gotcha! Wild Eevee was caught! Registered in Pokédex! ⭐',
    coachHint: 'Pikachu says: Move your Pawn all the way to e8 to evolve into a Queen!',
  },
];
