// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_rattata_0',
  pokemonName: 'Rattata',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Rattata\'s King Pawn Push! ⭐',
  prompt: 'A Wild Rattata appeared in Indigo League! Advance your Pawn to e4 to control the center!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e4' },
  rewardText: 'Gotcha! Wild Rattata was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e4!',
};
