// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_ekans_1_26',
  pokemonName: 'Ekans',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Ekans\'s Back-Rank Checkmate! ⭐',
  prompt: 'A Wild Ekans appeared in Indigo League! Slide your Rook all the way down to a8 for Checkmate!',
  fen: '5k2/4ppp1/8/8/8/8/8/R1K5 w - - 0 1',
  solutionMove: { from: 'a1', to: 'a8' },
  rewardText: 'Gotcha! Wild Ekans was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook to a8 — the King is trapped behind its own Pawns!',
};
