// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_oddish_5',
  pokemonName: 'Oddish',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Oddish\'s Fianchetto Setup! 🌿',
  prompt: 'A Wild Oddish appeared in Petalburg Woods! Push your Pawn to g3 to open a path for your Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g2', to: 'g3' },
  rewardText: 'Gotcha! Wild Oddish was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from g2 to g3!',
};
