// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_swinub_3_37',
  pokemonName: 'Swinub',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Swinub\'s Knight Fork! ❄️',
  prompt: 'A Wild Swinub appeared in Shoal Ice Cave! Fork the King and the Bishop — jump your Knight to d7!',
  fen: '1b3k2/4ppp1/1N6/8/8/8/8/5K2 w - - 0 1',
  solutionMoves: [{ from: 'b6', to: 'd7' }, { from: 'f8', to: 'e8' }, { from: 'd7', to: 'b8' }],
  stepHints: ['Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!', 'Pikachu says: The King had to run. Now capture the Bishop with your Knight on b8!'],
  rewardText: 'Gotcha! Wild Swinub was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!',
};
