// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_elekid_5',
  pokemonName: 'Elekid',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/239.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Elekid\'s Fianchetto Setup! ⚡',
  prompt: 'A Wild Elekid appeared in Mauville Plant! Push your Pawn to g3 to open a path for your Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g2', to: 'g3' },
  rewardText: 'Gotcha! Wild Elekid was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from g2 to g3!',
};
