// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_jynx_7',
  pokemonName: 'Jynx',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Jynx\'s Solid Pawn Push! ❄️',
  prompt: 'A Wild Jynx appeared in Shoal Ice Cave! Push your Pawn to e3 — a safe, solid start!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e3' },
  rewardText: 'Gotcha! Wild Jynx was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e3!',
};
