// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_delibird_3_39',
  pokemonName: 'Delibird',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Delibird\'s Mate in Two! ❄️',
  prompt: 'A Wild Delibird appeared in Shoal Ice Cave! Checkmate in 2! First, jump your Knight to f7 for check.',
  fen: '7k/R7/6K1/6N1/8/8/8/8 w - - 0 1',
  solutionMoves: [{ from: 'g5', to: 'f7' }, { from: 'h8', to: 'g8' }, { from: 'a7', to: 'a8' }],
  stepHints: ['Pikachu says: Jump your Knight to f7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to a8 for Checkmate!'],
  rewardText: 'Gotcha! Wild Delibird was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Jump your Knight to f7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
