// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_ponyta_2',
  pokemonName: 'Ponyta',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Ponyta\'s Knight Development! 🌋',
  prompt: 'A Wild Ponyta appeared in Mt. Chimney Volcano! Develop your Knight to f3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g1', to: 'f3' },
  rewardText: 'Gotcha! Wild Ponyta was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from g1 to f3!',
};
