// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_geodude_5',
  pokemonName: 'Geodude',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Geodude\'s Fianchetto Setup! ⭐',
  prompt: 'A Wild Geodude appeared in Indigo League! Push your Pawn to g3 to open a path for your Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g2', to: 'g3' },
  rewardText: 'Gotcha! Wild Geodude was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from g2 to g3!',
};
