// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_bulbasaur_14',
  pokemonName: 'Bulbasaur',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 30,
  title: 'Bulbasaur\'s Knight Snack! ⭐',
  prompt: 'A Wild Bulbasaur appeared in Indigo League! Capture the Bishop on d6 with your Knight!',
  fen: '7k/8/3b4/5N2/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'f5', to: 'd6' },
  rewardText: 'Gotcha! Wild Bulbasaur was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from f5 to d6 to grab the Bishop!',
};
