// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_piloswine_8',
  pokemonName: 'Piloswine',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/221.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Piloswine\'s Free Pawn Capture! ❄️',
  prompt: 'A Wild Piloswine appeared in Shoal Ice Cave! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/4P3/8/8/K7 w - - 0 1',
  solutionMove: { from: 'e4', to: 'd5' },
  rewardText: 'Gotcha! Wild Piloswine was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from e4 to d5 to grab the Pawn!',
};
