// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_rattata_1_18',
  pokemonName: 'Rattata',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Rattata\'s Rook Swoop! ⭐',
  prompt: 'A Wild Rattata appeared in Indigo League! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Rattata was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
