// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_pichu_1_15',
  pokemonName: 'Pichu',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/172.png',
  type: 'Bishop Dive',
  difficulty: 'medium',
  weight: 30,
  title: 'Pichu\'s Bishop Dive! ⚡',
  prompt: 'A Wild Pichu appeared in Mauville Plant! Capture the Pawn on f7 with your Bishop!',
  fen: 'k7/5p2/8/8/2B5/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'c4', to: 'f7' },
  rewardText: 'Gotcha! Wild Pichu was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Bishop from c4 to f7 to grab the Pawn!',
};
