// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_skarmory_2_29',
  pokemonName: 'Skarmory',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Skarmory\'s Queen Corner Checkmate! ⚡',
  prompt: 'A Wild Skarmory appeared in Mauville Plant! Bring your Queen to e8 for Checkmate — your King has already cut off the escape!',
  fen: '7k/8/6K1/8/8/8/8/4Q3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Skarmory was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Queen to e8. Your King blocks two escape squares, and your Queen covers the rest!',
};
