// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_smoochum_1_16',
  pokemonName: 'Smoochum',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/238.png',
  type: 'Long Diagonal Snipe',
  difficulty: 'medium',
  weight: 30,
  title: 'Smoochum\'s Long Diagonal Snipe! ❄️',
  prompt: 'A Wild Smoochum appeared in Shoal Ice Cave! Capture the Pawn on b7 with your Bishop!',
  fen: '7k/1p6/8/8/8/8/6B1/K7 w - - 0 1',
  solutionMove: { from: 'g2', to: 'b7' },
  rewardText: 'Gotcha! Wild Smoochum was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Bishop from g2 to b7 to grab the Pawn!',
};
