// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_wooper_1_21',
  pokemonName: 'Wooper',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/194.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Wooper\'s Queen Strike! 💧',
  prompt: 'A Wild Wooper appeared in Sootopolis Lake! Capture the Rook on d7 with your Queen!',
  fen: '7k/3r4/8/8/Q7/8/8/K7 w - - 0 1',
  solutionMove: { from: 'a4', to: 'd7' },
  rewardText: 'Gotcha! Wild Wooper was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Queen from a4 to d7 to grab the Rook!',
};
