// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_magby_1_20',
  pokemonName: 'Magby',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/240.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Magby\'s Queen Strike! 🌋',
  prompt: 'A Wild Magby appeared in Mt. Chimney Volcano! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Magby was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
