// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_charmeleon_2_28',
  pokemonName: 'Charmeleon',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Charmeleon\'s Queen Corner Checkmate! 🌋',
  prompt: 'A Wild Charmeleon appeared in Mt. Chimney Volcano! Bring your Queen to d8 for Checkmate — your King has already cut off the escape!',
  fen: 'k7/8/1K6/8/8/8/8/3Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd8' },
  rewardText: 'Gotcha! Wild Charmeleon was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Queen to d8. Your King blocks two escape squares, and your Queen covers the rest!',
};
