// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_swinub_2_25',
  pokemonName: 'Swinub',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Swinub\'s Back-Rank Checkmate! ❄️',
  prompt: 'A Wild Swinub appeared in Shoal Ice Cave! Slide your Rook all the way down to h8 for Checkmate!',
  fen: '4k3/3ppp2/8/8/8/8/8/1K5R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h8' },
  rewardText: 'Gotcha! Wild Swinub was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook to h8 — the King is trapped behind its own Pawns!',
};
