// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_nidoran_17',
  pokemonName: 'Nidoran',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Nidoran\'s Rook Swoop! ⭐',
  prompt: 'A Wild Nidoran appeared in Indigo League! Capture the Pawn on h6 with your Rook!',
  fen: 'k7/8/7p/8/8/8/8/K6R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h6' },
  rewardText: 'Gotcha! Wild Nidoran was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook from h1 to h6 to grab the Pawn!',
};
