// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_psyduck_1_21',
  pokemonName: 'Psyduck',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Psyduck\'s Queen Strike! ⭐',
  prompt: 'A Wild Psyduck appeared in Indigo League! Capture the Rook on d7 with your Queen!',
  fen: '7k/3r4/8/8/Q7/8/8/K7 w - - 0 1',
  solutionMove: { from: 'a4', to: 'd7' },
  rewardText: 'Gotcha! Wild Psyduck was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Queen from a4 to d7 to grab the Rook!',
};
