// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_wingull_11',
  pokemonName: 'Wingull',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/278.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Wingull\'s Knight Snack! 💧',
  prompt: 'A Wild Wingull appeared in Sootopolis Lake! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Wingull was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
