// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_nincada_20',
  pokemonName: 'Nincada',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/290.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Nincada\'s Queen Strike! 🌿',
  prompt: 'A Wild Nincada appeared in Petalburg Woods! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Nincada was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
