// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_wingull_1_27',
  pokemonName: 'Wingull',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/278.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Wingull\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Wingull appeared in Sootopolis Lake! Slide your Rook all the way down to b8 for Checkmate!',
  fen: '6k1/5ppp/8/8/8/8/8/1R1K4 w - - 0 1',
  solutionMove: { from: 'b1', to: 'b8' },
  rewardText: 'Gotcha! Wild Wingull was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to b8 — the King is trapped behind its own Pawns!',
};
