// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_delibird_2_27',
  pokemonName: 'Delibird',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Delibird\'s Back-Rank Checkmate! ❄️',
  prompt: 'A Wild Delibird appeared in Shoal Ice Cave! Slide your Rook all the way down to b8 for Checkmate!',
  fen: '6k1/5ppp/8/8/8/8/8/1R1K4 w - - 0 1',
  solutionMove: { from: 'b1', to: 'b8' },
  rewardText: 'Gotcha! Wild Delibird was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook to b8 — the King is trapped behind its own Pawns!',
};
