// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_mudkip_1_26',
  pokemonName: 'Mudkip',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Mudkip\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Mudkip appeared in Sootopolis Lake! Slide your Rook all the way down to a8 for Checkmate!',
  fen: '5k2/4ppp1/8/8/8/8/8/R1K5 w - - 0 1',
  solutionMove: { from: 'a1', to: 'a8' },
  rewardText: 'Gotcha! Wild Mudkip was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to a8 — the King is trapped behind its own Pawns!',
};
