// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_shroomish_19',
  pokemonName: 'Shroomish',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/285.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Shroomish\'s Rook Swoop! 🌿',
  prompt: 'A Wild Shroomish appeared in Petalburg Woods! Capture the Knight on e6 with your Rook!',
  fen: '7k/8/4n3/8/8/8/8/K3R3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e6' },
  rewardText: 'Gotcha! Wild Shroomish was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook from e1 to e6 to grab the Knight!',
};
