// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_swinub_1',
  pokemonName: 'Swinub',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Swinub\'s Queen Pawn Push! ❄️',
  prompt: 'A Wild Swinub appeared in Shoal Ice Cave! Push your Queen Pawn to d4 to claim the middle!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'd2', to: 'd4' },
  rewardText: 'Gotcha! Wild Swinub was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from d2 to d4!',
};
