// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_glalie_1_21',
  pokemonName: 'Glalie',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/362.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Glalie\'s Queen Strike! ❄️',
  prompt: 'A Wild Glalie appeared in Shoal Ice Cave! Capture the Rook on d7 with your Queen!',
  fen: '7k/3r4/8/8/Q7/8/8/K7 w - - 0 1',
  solutionMove: { from: 'a4', to: 'd7' },
  rewardText: 'Gotcha! Wild Glalie was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Queen from a4 to d7 to grab the Rook!',
};
