// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_volbeat_21',
  pokemonName: 'Volbeat',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/313.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Volbeat\'s Queen Strike! 🌿',
  prompt: 'A Wild Volbeat appeared in Petalburg Woods! Capture the Rook on d7 with your Queen!',
  fen: '7k/3r4/8/8/Q7/8/8/K7 w - - 0 1',
  solutionMove: { from: 'a4', to: 'd7' },
  rewardText: 'Gotcha! Wild Volbeat was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Queen from a4 to d7 to grab the Rook!',
};
