// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_sneasel_2',
  pokemonName: 'Sneasel',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Sneasel\'s Knight Development! ❄️',
  prompt: 'A Wild Sneasel appeared in Shoal Ice Cave! Develop your Knight to f3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g1', to: 'f3' },
  rewardText: 'Gotcha! Wild Sneasel was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Knight from g1 to f3!',
};
