// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_venonat_7',
  pokemonName: 'Venonat',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Venonat\'s Solid Pawn Push! 🌿',
  prompt: 'A Wild Venonat appeared in Petalburg Woods! Push your Pawn to e3 — a safe, solid start!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e3' },
  rewardText: 'Gotcha! Wild Venonat was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e3!',
};
