// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_aron_8',
  pokemonName: 'Aron',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/304.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Aron\'s Free Pawn Capture! ⚡',
  prompt: 'A Wild Aron appeared in Mauville Plant! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/4P3/8/8/K7 w - - 0 1',
  solutionMove: { from: 'e4', to: 'd5' },
  rewardText: 'Gotcha! Wild Aron was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from e4 to d5 to grab the Pawn!',
};
