// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_growlithe_1',
  pokemonName: 'Growlithe',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Growlithe\'s Queen Pawn Push! 🌋',
  prompt: 'A Wild Growlithe appeared in Mt. Chimney Volcano! Push your Queen Pawn to d4 to claim the middle!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'd2', to: 'd4' },
  rewardText: 'Gotcha! Wild Growlithe was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Pawn from d2 to d4!',
};
