// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_plusle_1_13',
  pokemonName: 'Plusle',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/311.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Plusle\'s Knight Snack! ⚡',
  prompt: 'A Wild Plusle appeared in Mauville Plant! Capture the Pawn on d5 with your Knight!',
  fen: '7k/8/8/3p4/8/2N5/8/6K1 w - - 0 1',
  solutionMove: { from: 'c3', to: 'd5' },
  rewardText: 'Gotcha! Wild Plusle was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Knight from c3 to d5 to grab the Pawn!',
};
