// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_horsea_2_34',
  pokemonName: 'Horsea',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Horsea\'s Knight Fork! 💧',
  prompt: 'A Wild Horsea appeared in Sootopolis Lake! Fork the King and the Rook — jump your Knight to c7!',
  fen: 'r3k3/3ppp2/N7/8/8/8/8/4K3 w - - 0 1',
  solutionMoves: [{ from: 'a6', to: 'c7' }, { from: 'e8', to: 'd8' }, { from: 'c7', to: 'a8' }],
  stepHints: ['Pikachu says: Jump your Knight to c7 — check! It also attacks the Rook on a8!', 'Pikachu says: The King had to run. Now capture the Rook with your Knight on a8!'],
  rewardText: 'Gotcha! Wild Horsea was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Jump your Knight to c7 — check! It also attacks the Rook on a8!',
};
