// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_geodude_1_23',
  pokemonName: 'Geodude',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Geodude\'s Back-Rank Checkmate! ⭐',
  prompt: 'A Wild Geodude appeared in Indigo League! Slide your Rook all the way down to f8 for Checkmate!',
  fen: '2k5/1ppp4/8/8/8/8/8/5R1K w - - 0 1',
  solutionMove: { from: 'f1', to: 'f8' },
  rewardText: 'Gotcha! Wild Geodude was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook to f8 — the King is trapped behind its own Pawns!',
};
