// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_torkoal_1_19',
  pokemonName: 'Torkoal',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/324.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Torkoal\'s Rook Swoop! 🌋',
  prompt: 'A Wild Torkoal appeared in Mt. Chimney Volcano! Capture the Knight on e6 with your Rook!',
  fen: '7k/8/4n3/8/8/8/8/K3R3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e6' },
  rewardText: 'Gotcha! Wild Torkoal was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook from e1 to e6 to grab the Knight!',
};
