// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_staryu_1_20',
  pokemonName: 'Staryu',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Staryu\'s Queen Strike! 💧',
  prompt: 'A Wild Staryu appeared in Sootopolis Lake! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Staryu was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
