// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_growlithe_1_13',
  pokemonName: 'Growlithe',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Growlithe\'s Knight Snack! 🌋',
  prompt: 'A Wild Growlithe appeared in Mt. Chimney Volcano! Capture the Pawn on d5 with your Knight!',
  fen: '7k/8/8/3p4/8/2N5/8/6K1 w - - 0 1',
  solutionMove: { from: 'c3', to: 'd5' },
  rewardText: 'Gotcha! Wild Growlithe was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from c3 to d5 to grab the Pawn!',
};
