// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_charmeleon_1_16',
  pokemonName: 'Charmeleon',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
  type: 'Long Diagonal Snipe',
  difficulty: 'medium',
  weight: 30,
  title: 'Charmeleon\'s Long Diagonal Snipe! 🌋',
  prompt: 'A Wild Charmeleon appeared in Mt. Chimney Volcano! Capture the Pawn on b7 with your Bishop!',
  fen: '7k/1p6/8/8/8/8/6B1/K7 w - - 0 1',
  solutionMove: { from: 'g2', to: 'b7' },
  rewardText: 'Gotcha! Wild Charmeleon was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Bishop from g2 to b7 to grab the Pawn!',
};
