// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_clefairy_11',
  pokemonName: 'Clefairy',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Clefairy\'s Knight Snack! ⭐',
  prompt: 'A Wild Clefairy appeared in Indigo League! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Clefairy was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
