// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_yanma_1_37',
  pokemonName: 'Yanma',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/193.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Yanma\'s Knight Fork! 🌿',
  prompt: 'A Wild Yanma appeared in Petalburg Woods! Fork the King and the Bishop — jump your Knight to d7!',
  fen: '1b3k2/4ppp1/1N6/8/8/8/8/5K2 w - - 0 1',
  solutionMoves: [{ from: 'b6', to: 'd7' }, { from: 'f8', to: 'e8' }, { from: 'd7', to: 'b8' }],
  stepHints: ['Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!', 'Pikachu says: The King had to run. Now capture the Bishop with your Knight on b8!'],
  rewardText: 'Gotcha! Wild Yanma was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!',
};
