// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_camerupt_1_23',
  pokemonName: 'Camerupt',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/323.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Camerupt\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Camerupt appeared in Mt. Chimney Volcano! Slide your Rook all the way down to f8 for Checkmate!',
  fen: '2k5/1ppp4/8/8/8/8/8/5R1K w - - 0 1',
  solutionMove: { from: 'f1', to: 'f8' },
  rewardText: 'Gotcha! Wild Camerupt was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to f8 — the King is trapped behind its own Pawns!',
};
