// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_magmar_3',
  pokemonName: 'Magmar',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Magmar\'s Knight Development! 🌋',
  prompt: 'A Wild Magmar appeared in Mt. Chimney Volcano! Develop your Knight to c3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b1', to: 'c3' },
  rewardText: 'Gotcha! Wild Magmar was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from b1 to c3!',
};
