// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_numel_2_30',
  pokemonName: 'Numel',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/322.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Numel\'s Queen Corner Checkmate! 🌋',
  prompt: 'A Wild Numel appeared in Mt. Chimney Volcano! Bring your Queen to d1 for Checkmate — your King has already cut off the escape!',
  fen: '3Q4/8/8/8/8/1K6/8/k7 w - - 0 1',
  solutionMove: { from: 'd8', to: 'd1' },
  rewardText: 'Gotcha! Wild Numel was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Queen to d1. Your King blocks two escape squares, and your Queen covers the rest!',
};
