// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_elekid_1_16',
  pokemonName: 'Elekid',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/239.png',
  type: 'Long Diagonal Snipe',
  difficulty: 'medium',
  weight: 30,
  title: 'Elekid\'s Long Diagonal Snipe! ⚡',
  prompt: 'A Wild Elekid appeared in Mauville Plant! Capture the Pawn on b7 with your Bishop!',
  fen: '7k/1p6/8/8/8/8/6B1/K7 w - - 0 1',
  solutionMove: { from: 'g2', to: 'b7' },
  rewardText: 'Gotcha! Wild Elekid was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Bishop from g2 to b7 to grab the Pawn!',
};
