// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_spheal_2_24',
  pokemonName: 'Spheal',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/363.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Spheal\'s Back-Rank Checkmate! ❄️',
  prompt: 'A Wild Spheal appeared in Shoal Ice Cave! Slide your Rook all the way down to g8 for Checkmate!',
  fen: '3k4/2ppp3/8/8/8/8/8/K5R1 w - - 0 1',
  solutionMove: { from: 'g1', to: 'g8' },
  rewardText: 'Gotcha! Wild Spheal was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook to g8 — the King is trapped behind its own Pawns!',
};
