// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_metapod_1_25',
  pokemonName: 'Metapod',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Metapod\'s Back-Rank Checkmate! 🌿',
  prompt: 'A Wild Metapod appeared in Petalburg Woods! Slide your Rook all the way down to h8 for Checkmate!',
  fen: '4k3/3ppp2/8/8/8/8/8/1K5R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h8' },
  rewardText: 'Gotcha! Wild Metapod was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook to h8 — the King is trapped behind its own Pawns!',
};
