// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_goldeen_1_19',
  pokemonName: 'Goldeen',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Goldeen\'s Rook Swoop! 💧',
  prompt: 'A Wild Goldeen appeared in Sootopolis Lake! Capture the Knight on e6 with your Rook!',
  fen: '7k/8/4n3/8/8/8/8/K3R3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e6' },
  rewardText: 'Gotcha! Wild Goldeen was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook from e1 to e6 to grab the Knight!',
};
