// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_staryu_2_36',
  pokemonName: 'Staryu',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Staryu\'s Knight Fork! 💧',
  prompt: 'A Wild Staryu appeared in Sootopolis Lake! Fork the King and the Rook — jump your Knight to d7!',
  fen: '1r3k2/4ppp1/1N6/8/8/8/8/5K2 w - - 0 1',
  solutionMoves: [{ from: 'b6', to: 'd7' }, { from: 'f8', to: 'e8' }, { from: 'd7', to: 'b8' }],
  stepHints: ['Pikachu says: Jump your Knight to d7 — check! It also attacks the Rook on b8!', 'Pikachu says: The King had to run. Now capture the Rook with your Knight on b8!'],
  rewardText: 'Gotcha! Wild Staryu was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Jump your Knight to d7 — check! It also attacks the Rook on b8!',
};
