// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_caterpie_1_24',
  pokemonName: 'Caterpie',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Caterpie\'s Back-Rank Checkmate! 🌿',
  prompt: 'A Wild Caterpie appeared in Petalburg Woods! Slide your Rook all the way down to g8 for Checkmate!',
  fen: '3k4/2ppp3/8/8/8/8/8/K5R1 w - - 0 1',
  solutionMove: { from: 'g1', to: 'g8' },
  rewardText: 'Gotcha! Wild Caterpie was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook to g8 — the King is trapped behind its own Pawns!',
};
