// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_numel_1_18',
  pokemonName: 'Numel',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/322.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Numel\'s Rook Swoop! 🌋',
  prompt: 'A Wild Numel appeared in Mt. Chimney Volcano! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Numel was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
