// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_sandshrew_1_27',
  pokemonName: 'Sandshrew',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Sandshrew\'s Back-Rank Checkmate! ⭐',
  prompt: 'A Wild Sandshrew appeared in Indigo League! Slide your Rook all the way down to b8 for Checkmate!',
  fen: '6k1/5ppp/8/8/8/8/8/1R1K4 w - - 0 1',
  solutionMove: { from: 'b1', to: 'b8' },
  rewardText: 'Gotcha! Wild Sandshrew was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook to b8 — the King is trapped behind its own Pawns!',
};
