// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_pidgey_1',
  pokemonName: 'Pidgey',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Pidgey\'s Queen Pawn Push! ⭐',
  prompt: 'A Wild Pidgey appeared in Indigo League! Push your Queen Pawn to d4 to claim the middle!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'd2', to: 'd4' },
  rewardText: 'Gotcha! Wild Pidgey was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from d2 to d4!',
};
