// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_barboach_1_30',
  pokemonName: 'Barboach',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/339.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Barboach\'s Queen Corner Checkmate! 💧',
  prompt: 'A Wild Barboach appeared in Sootopolis Lake! Bring your Queen to d1 for Checkmate — your King has already cut off the escape!',
  fen: '3Q4/8/8/8/8/1K6/8/k7 w - - 0 1',
  solutionMove: { from: 'd8', to: 'd1' },
  rewardText: 'Gotcha! Wild Barboach was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Queen to d1. Your King blocks two escape squares, and your Queen covers the rest!',
};
