// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_magneton_6',
  pokemonName: 'Magneton',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Magneton\'s Fianchetto Setup! ⚡',
  prompt: 'A Wild Magneton appeared in Mauville Plant! Push your Pawn to b3 to open a path for your other Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b2', to: 'b3' },
  rewardText: 'Gotcha! Wild Magneton was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from b2 to b3!',
};
