// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_combusken_10',
  pokemonName: 'Combusken',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Combusken\'s Free Pawn Capture! 🌋',
  prompt: 'A Wild Combusken appeared in Mt. Chimney Volcano! Capture the Pawn on e5 with your Pawn!',
  fen: '7k/8/8/4p3/5P2/8/8/K7 w - - 0 1',
  solutionMove: { from: 'f4', to: 'e5' },
  rewardText: 'Gotcha! Wild Combusken was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Pawn from f4 to e5 to grab the Pawn!',
};
