// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_clamperl_1_31',
  pokemonName: 'Clamperl',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/366.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Clamperl\'s Queen Corner Checkmate! 💧',
  prompt: 'A Wild Clamperl appeared in Sootopolis Lake! Bring your Queen to e1 for Checkmate — your King has already cut off the escape!',
  fen: '4Q3/8/8/8/8/6K1/8/7k w - - 0 1',
  solutionMove: { from: 'e8', to: 'e1' },
  rewardText: 'Gotcha! Wild Clamperl was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Queen to e1. Your King blocks two escape squares, and your Queen covers the rest!',
};
