// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_mareep_1_20',
  pokemonName: 'Mareep',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/179.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Mareep\'s Queen Strike! ⚡',
  prompt: 'A Wild Mareep appeared in Mauville Plant! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Mareep was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
