// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_smoochum_4',
  pokemonName: 'Smoochum',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/238.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Smoochum\'s Wing Pawn Push! ❄️',
  prompt: 'A Wild Smoochum appeared in Shoal Ice Cave! Advance your Pawn to c4 for extra space!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'c2', to: 'c4' },
  rewardText: 'Gotcha! Wild Smoochum was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from c2 to c4!',
};
