// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_jigglypuff_10',
  pokemonName: 'Jigglypuff',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Jigglypuff\'s Free Pawn Capture! ⭐',
  prompt: 'A Wild Jigglypuff appeared in Indigo League! Capture the Pawn on e5 with your Pawn!',
  fen: '7k/8/8/4p3/5P2/8/8/K7 w - - 0 1',
  solutionMove: { from: 'f4', to: 'e5' },
  rewardText: 'Gotcha! Wild Jigglypuff was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from f4 to e5 to grab the Pawn!',
};
