// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_machop_4',
  pokemonName: 'Machop',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Machop\'s Wing Pawn Push! ⭐',
  prompt: 'A Wild Machop appeared in Indigo League! Advance your Pawn to c4 for extra space!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'c2', to: 'c4' },
  rewardText: 'Gotcha! Wild Machop was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from c2 to c4!',
};
