// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_weedle_1_26',
  pokemonName: 'Weedle',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Weedle\'s Back-Rank Checkmate! 🌿',
  prompt: 'A Wild Weedle appeared in Petalburg Woods! Slide your Rook all the way down to a8 for Checkmate!',
  fen: '5k2/4ppp1/8/8/8/8/8/R1K5 w - - 0 1',
  solutionMove: { from: 'a1', to: 'a8' },
  rewardText: 'Gotcha! Wild Weedle was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook to a8 — the King is trapped behind its own Pawns!',
};
