// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_pidgey_1_19',
  pokemonName: 'Pidgey',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Pidgey\'s Rook Swoop! ⭐',
  prompt: 'A Wild Pidgey appeared in Indigo League! Capture the Knight on e6 with your Rook!',
  fen: '7k/8/4n3/8/8/8/8/K3R3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e6' },
  rewardText: 'Gotcha! Wild Pidgey was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook from e1 to e6 to grab the Knight!',
};
