// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_abra_6',
  pokemonName: 'Abra',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Abra\'s Fianchetto Setup! ⭐',
  prompt: 'A Wild Abra appeared in Indigo League! Push your Pawn to b3 to open a path for your other Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b2', to: 'b3' },
  rewardText: 'Gotcha! Wild Abra was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from b2 to b3!',
};
