// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_cloyster_1_23',
  pokemonName: 'Cloyster',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Cloyster\'s Back-Rank Checkmate! ❄️',
  prompt: 'A Wild Cloyster appeared in Shoal Ice Cave! Slide your Rook all the way down to f8 for Checkmate!',
  fen: '2k5/1ppp4/8/8/8/8/8/5R1K w - - 0 1',
  solutionMove: { from: 'f1', to: 'f8' },
  rewardText: 'Gotcha! Wild Cloyster was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook to f8 — the King is trapped behind its own Pawns!',
};
