// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_surskit_18',
  pokemonName: 'Surskit',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/283.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Surskit\'s Rook Swoop! 🌿',
  prompt: 'A Wild Surskit appeared in Petalburg Woods! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Surskit was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
