// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_charmeleon_4',
  pokemonName: 'Charmeleon',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Charmeleon\'s Wing Pawn Push! 🌋',
  prompt: 'A Wild Charmeleon appeared in Mt. Chimney Volcano! Advance your Pawn to c4 for extra space!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'c2', to: 'c4' },
  rewardText: 'Gotcha! Wild Charmeleon was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Pawn from c2 to c4!',
};
