// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_magmar_3_39',
  pokemonName: 'Magmar',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Magmar\'s Mate in Two! 🌋',
  prompt: 'A Wild Magmar appeared in Mt. Chimney Volcano! Checkmate in 2! First, jump your Knight to f7 for check.',
  fen: '7k/R7/6K1/6N1/8/8/8/8 w - - 0 1',
  solutionMoves: [{ from: 'g5', to: 'f7' }, { from: 'h8', to: 'g8' }, { from: 'a7', to: 'a8' }],
  stepHints: ['Pikachu says: Jump your Knight to f7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to a8 for Checkmate!'],
  rewardText: 'Gotcha! Wild Magmar was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Jump your Knight to f7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
