// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_magikarp_1_25',
  pokemonName: 'Magikarp',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Magikarp\'s Back-Rank Checkmate! ⭐',
  prompt: 'A Wild Magikarp appeared in Indigo League! Slide your Rook all the way down to h8 for Checkmate!',
  fen: '4k3/3ppp2/8/8/8/8/8/1K5R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h8' },
  rewardText: 'Gotcha! Wild Magikarp was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook to h8 — the King is trapped behind its own Pawns!',
};
