// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_horsea_2',
  pokemonName: 'Horsea',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Horsea\'s Knight Development! 💧',
  prompt: 'A Wild Horsea appeared in Sootopolis Lake! Develop your Knight to f3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g1', to: 'f3' },
  rewardText: 'Gotcha! Wild Horsea was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Knight from g1 to f3!',
};
