// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_cloyster_11',
  pokemonName: 'Cloyster',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Cloyster\'s Knight Snack! ❄️',
  prompt: 'A Wild Cloyster appeared in Shoal Ice Cave! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Cloyster was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
