// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_skarmory_1_18',
  pokemonName: 'Skarmory',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Skarmory\'s Rook Swoop! ⚡',
  prompt: 'A Wild Skarmory appeared in Mauville Plant! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Skarmory was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
