// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_barboach_14',
  pokemonName: 'Barboach',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/339.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 30,
  title: 'Barboach\'s Knight Snack! 💧',
  prompt: 'A Wild Barboach appeared in Sootopolis Lake! Capture the Bishop on d6 with your Knight!',
  fen: '7k/8/3b4/5N2/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'f5', to: 'd6' },
  rewardText: 'Gotcha! Wild Barboach was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Knight from f5 to d6 to grab the Bishop!',
};
