// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_ekans_8',
  pokemonName: 'Ekans',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Ekans\'s Free Pawn Capture! ⭐',
  prompt: 'A Wild Ekans appeared in Indigo League! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/4P3/8/8/K7 w - - 0 1',
  solutionMove: { from: 'e4', to: 'd5' },
  rewardText: 'Gotcha! Wild Ekans was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from e4 to d5 to grab the Pawn!',
};
