// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_beedrill_1_28',
  pokemonName: 'Beedrill',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Beedrill\'s Queen Corner Checkmate! 🌿',
  prompt: 'A Wild Beedrill appeared in Petalburg Woods! Bring your Queen to d8 for Checkmate — your King has already cut off the escape!',
  fen: 'k7/8/1K6/8/8/8/8/3Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd8' },
  rewardText: 'Gotcha! Wild Beedrill was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Queen to d8. Your King blocks two escape squares, and your Queen covers the rest!',
};
