// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_paras_6',
  pokemonName: 'Paras',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Paras\'s Fianchetto Setup! 🌿',
  prompt: 'A Wild Paras appeared in Petalburg Woods! Push your Pawn to b3 to open a path for your other Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b2', to: 'b3' },
  rewardText: 'Gotcha! Wild Paras was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from b2 to b3!',
};
