// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_yanma_13',
  pokemonName: 'Yanma',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/193.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Yanma\'s Knight Snack! 🌿',
  prompt: 'A Wild Yanma appeared in Petalburg Woods! Capture the Pawn on d5 with your Knight!',
  fen: '7k/8/8/3p4/8/2N5/8/6K1 w - - 0 1',
  solutionMove: { from: 'c3', to: 'd5' },
  rewardText: 'Gotcha! Wild Yanma was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from c3 to d5 to grab the Pawn!',
};
