// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_combusken_1_22',
  pokemonName: 'Combusken',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Combusken\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Combusken appeared in Mt. Chimney Volcano! Slide your Rook all the way down to e8 for Checkmate!',
  fen: '1k6/ppp5/8/8/8/8/8/4R1K1 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Combusken was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to e8 — the King is trapped behind its own Pawns!',
};
