// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_spearow_1_34',
  pokemonName: 'Spearow',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Spearow\'s Knight Fork! ⭐',
  prompt: 'A Wild Spearow appeared in Indigo League! Fork the King and the Rook — jump your Knight to c7!',
  fen: 'r3k3/3ppp2/N7/8/8/8/8/4K3 w - - 0 1',
  solutionMoves: [{ from: 'a6', to: 'c7' }, { from: 'e8', to: 'd8' }, { from: 'c7', to: 'a8' }],
  stepHints: ['Pikachu says: Jump your Knight to c7 — check! It also attacks the Rook on a8!', 'Pikachu says: The King had to run. Now capture the Rook with your Knight on a8!'],
  rewardText: 'Gotcha! Wild Spearow was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Jump your Knight to c7 — check! It also attacks the Rook on a8!',
};
