// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_psyduck_3',
  pokemonName: 'Psyduck',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Psyduck\'s Knight Development! ⭐',
  prompt: 'A Wild Psyduck appeared in Indigo League! Develop your Knight to c3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b1', to: 'c3' },
  rewardText: 'Gotcha! Wild Psyduck was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from b1 to c3!',
};
