// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_cascoon_16',
  pokemonName: 'Cascoon',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/268.png',
  type: 'Long Diagonal Snipe',
  difficulty: 'medium',
  weight: 30,
  title: 'Cascoon\'s Long Diagonal Snipe! 🌿',
  prompt: 'A Wild Cascoon appeared in Petalburg Woods! Capture the Pawn on b7 with your Bishop!',
  fen: '7k/1p6/8/8/8/8/6B1/K7 w - - 0 1',
  solutionMove: { from: 'g2', to: 'b7' },
  rewardText: 'Gotcha! Wild Cascoon was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Bishop from g2 to b7 to grab the Pawn!',
};
