// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_minun_3',
  pokemonName: 'Minun',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/312.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Minun\'s Knight Development! ⚡',
  prompt: 'A Wild Minun appeared in Mauville Plant! Develop your Knight to c3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b1', to: 'c3' },
  rewardText: 'Gotcha! Wild Minun was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Knight from b1 to c3!',
};
