// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_ponyta_1_14',
  pokemonName: 'Ponyta',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 30,
  title: 'Ponyta\'s Knight Snack! 🌋',
  prompt: 'A Wild Ponyta appeared in Mt. Chimney Volcano! Capture the Bishop on d6 with your Knight!',
  fen: '7k/8/3b4/5N2/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'f5', to: 'd6' },
  rewardText: 'Gotcha! Wild Ponyta was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from f5 to d6 to grab the Bishop!',
};
