// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_tentacool_2_33',
  pokemonName: 'Tentacool',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
  type: 'Knight Fork',
  difficulty: 'hard',
  weight: 16,
  title: 'Tentacool\'s Knight Fork! 💧',
  prompt: 'A Wild Tentacool appeared in Sootopolis Lake! Fork the King and the Queen — jump your Knight to e7!',
  fen: '2q3k1/5ppp/2N5/8/8/8/8/6K1 w - - 0 1',
  solutionMoves: [{ from: 'c6', to: 'e7' }, { from: 'g8', to: 'f8' }, { from: 'e7', to: 'c8' }],
  stepHints: ['Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!', 'Pikachu says: The King had to run. Now capture the Queen with your Knight on c8!'],
  rewardText: 'Gotcha! Wild Tentacool was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!',
};
