// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_pidgey_2_37',
  pokemonName: 'Pidgey',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Pidgey\'s Knight Fork! ⭐',
  prompt: 'A Wild Pidgey appeared in Indigo League! Fork the King and the Bishop — jump your Knight to d7!',
  fen: '1b3k2/4ppp1/1N6/8/8/8/8/5K2 w - - 0 1',
  solutionMoves: [{ from: 'b6', to: 'd7' }, { from: 'f8', to: 'e8' }, { from: 'd7', to: 'b8' }],
  stepHints: ['Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!', 'Pikachu says: The King had to run. Now capture the Bishop with your Knight on b8!'],
  rewardText: 'Gotcha! Wild Pidgey was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Jump your Knight to d7 — check! It also attacks the Bishop on b8!',
};
