// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_sneasel_3_38',
  pokemonName: 'Sneasel',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Sneasel\'s Mate in Two! ❄️',
  prompt: 'A Wild Sneasel appeared in Shoal Ice Cave! Checkmate in 2! First, jump your Knight to c7 for check.',
  fen: 'k7/7R/1K6/1N6/8/8/8/8 w - - 0 1',
  solutionMoves: [{ from: 'b5', to: 'c7' }, { from: 'a8', to: 'b8' }, { from: 'h7', to: 'h8' }],
  stepHints: ['Pikachu says: Jump your Knight to c7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to h8 for Checkmate!'],
  rewardText: 'Gotcha! Wild Sneasel was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Jump your Knight to c7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
