// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_plusle_2_24',
  pokemonName: 'Plusle',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/311.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Plusle\'s Back-Rank Checkmate! ⚡',
  prompt: 'A Wild Plusle appeared in Mauville Plant! Slide your Rook all the way down to g8 for Checkmate!',
  fen: '3k4/2ppp3/8/8/8/8/8/K5R1 w - - 0 1',
  solutionMove: { from: 'g1', to: 'g8' },
  rewardText: 'Gotcha! Wild Plusle was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook to g8 — the King is trapped behind its own Pawns!',
};
