// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_seedot_1_41',
  pokemonName: 'Seedot',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/273.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Seedot\'s Mate in Two! 🌿',
  prompt: 'A Wild Seedot appeared in Petalburg Woods! Checkmate in 2! First, jump your Knight to f2 for check.',
  fen: '8/8/8/8/6N1/6K1/R7/7k w - - 0 1',
  solutionMoves: [{ from: 'g4', to: 'f2' }, { from: 'h1', to: 'g1' }, { from: 'a2', to: 'a1' }],
  stepHints: ['Pikachu says: Jump your Knight to f2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to a1 for Checkmate!'],
  rewardText: 'Gotcha! Wild Seedot was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Jump your Knight to f2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
