// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_camerupt_2_35',
  pokemonName: 'Camerupt',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/323.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Camerupt\'s Knight Fork! 🌋',
  prompt: 'A Wild Camerupt appeared in Mt. Chimney Volcano! Fork the King and the Bishop — jump your Knight to c7!',
  fen: 'b3k3/3ppp2/N7/8/8/8/8/4K3 w - - 0 1',
  solutionMoves: [{ from: 'a6', to: 'c7' }, { from: 'e8', to: 'd8' }, { from: 'c7', to: 'a8' }],
  stepHints: ['Pikachu says: Jump your Knight to c7 — check! It also attacks the Bishop on a8!', 'Pikachu says: The King had to run. Now capture the Bishop with your Knight on a8!'],
  rewardText: 'Gotcha! Wild Camerupt was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Jump your Knight to c7 — check! It also attacks the Bishop on a8!',
};
