// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_weedle_2',
  pokemonName: 'Weedle',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Weedle\'s Knight Development! 🌿',
  prompt: 'A Wild Weedle appeared in Petalburg Woods! Develop your Knight to f3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g1', to: 'f3' },
  rewardText: 'Gotcha! Wild Weedle was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from g1 to f3!',
};
