// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_lapras_10',
  pokemonName: 'Lapras',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Lapras\'s Free Pawn Capture! ❄️',
  prompt: 'A Wild Lapras appeared in Shoal Ice Cave! Capture the Pawn on e5 with your Pawn!',
  fen: '7k/8/8/4p3/5P2/8/8/K7 w - - 0 1',
  solutionMove: { from: 'f4', to: 'e5' },
  rewardText: 'Gotcha! Wild Lapras was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from f4 to e5 to grab the Pawn!',
};
