// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_dewgong_5',
  pokemonName: 'Dewgong',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Dewgong\'s Fianchetto Setup! ❄️',
  prompt: 'A Wild Dewgong appeared in Shoal Ice Cave! Push your Pawn to g3 to open a path for your Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g2', to: 'g3' },
  rewardText: 'Gotcha! Wild Dewgong was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from g2 to g3!',
};
