// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_magmar_2_27',
  pokemonName: 'Magmar',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Magmar\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Magmar appeared in Mt. Chimney Volcano! Slide your Rook all the way down to b8 for Checkmate!',
  fen: '6k1/5ppp/8/8/8/8/8/1R1K4 w - - 0 1',
  solutionMove: { from: 'b1', to: 'b8' },
  rewardText: 'Gotcha! Wild Magmar was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to b8 — the King is trapped behind its own Pawns!',
};
