// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_magmar_1_15',
  pokemonName: 'Magmar',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
  type: 'Bishop Dive',
  difficulty: 'medium',
  weight: 30,
  title: 'Magmar\'s Bishop Dive! 🌋',
  prompt: 'A Wild Magmar appeared in Mt. Chimney Volcano! Capture the Pawn on f7 with your Bishop!',
  fen: 'k7/5p2/8/8/2B5/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'c4', to: 'f7' },
  rewardText: 'Gotcha! Wild Magmar was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Bishop from c4 to f7 to grab the Pawn!',
};
