// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_chinchou_8',
  pokemonName: 'Chinchou',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/170.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Chinchou\'s Free Pawn Capture! 💧',
  prompt: 'A Wild Chinchou appeared in Sootopolis Lake! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/4P3/8/8/K7 w - - 0 1',
  solutionMove: { from: 'e4', to: 'd5' },
  rewardText: 'Gotcha! Wild Chinchou was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from e4 to d5 to grab the Pawn!',
};
