// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_kakuna_3',
  pokemonName: 'Kakuna',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Kakuna\'s Knight Development! 🌿',
  prompt: 'A Wild Kakuna appeared in Petalburg Woods! Develop your Knight to c3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b1', to: 'c3' },
  rewardText: 'Gotcha! Wild Kakuna was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from b1 to c3!',
};
