// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_pineco_10',
  pokemonName: 'Pineco',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/204.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Pineco\'s Free Pawn Capture! 🌿',
  prompt: 'A Wild Pineco appeared in Petalburg Woods! Capture the Pawn on e5 with your Pawn!',
  fen: '7k/8/8/4p3/5P2/8/8/K7 w - - 0 1',
  solutionMove: { from: 'f4', to: 'e5' },
  rewardText: 'Gotcha! Wild Pineco was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from f4 to e5 to grab the Pawn!',
};
