// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_torchic_9',
  pokemonName: 'Torchic',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Torchic\'s Free Pawn Capture! 🌋',
  prompt: 'A Wild Torchic appeared in Mt. Chimney Volcano! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/2P5/8/8/K7 w - - 0 1',
  solutionMove: { from: 'c4', to: 'd5' },
  rewardText: 'Gotcha! Wild Torchic was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Pawn from c4 to d5 to grab the Pawn!',
};
