// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_poliwag_0',
  pokemonName: 'Poliwag',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Poliwag\'s King Pawn Push! 💧',
  prompt: 'A Wild Poliwag appeared in Sootopolis Lake! Advance your Pawn to e4 to control the center!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e4' },
  rewardText: 'Gotcha! Wild Poliwag was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e4!',
};
