// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_horsea_1_18',
  pokemonName: 'Horsea',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Horsea\'s Rook Swoop! 💧',
  prompt: 'A Wild Horsea appeared in Sootopolis Lake! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Horsea was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
