// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_aron_2_30',
  pokemonName: 'Aron',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/304.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Aron\'s Queen Corner Checkmate! ⚡',
  prompt: 'A Wild Aron appeared in Mauville Plant! Bring your Queen to d1 for Checkmate — your King has already cut off the escape!',
  fen: '3Q4/8/8/8/8/1K6/8/k7 w - - 0 1',
  solutionMove: { from: 'd8', to: 'd1' },
  rewardText: 'Gotcha! Wild Aron was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Queen to d1. Your King blocks two escape squares, and your Queen covers the rest!',
};
