// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_illumise_22',
  pokemonName: 'Illumise',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/314.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Illumise\'s Back-Rank Checkmate! 🌿',
  prompt: 'A Wild Illumise appeared in Petalburg Woods! Slide your Rook all the way down to e8 for Checkmate!',
  fen: '1k6/ppp5/8/8/8/8/8/4R1K1 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Illumise was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook to e8 — the King is trapped behind its own Pawns!',
};
