// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_roselia_23',
  pokemonName: 'Roselia',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/315.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Roselia\'s Back-Rank Checkmate! 🌿',
  prompt: 'A Wild Roselia appeared in Petalburg Woods! Slide your Rook all the way down to f8 for Checkmate!',
  fen: '2k5/1ppp4/8/8/8/8/8/5R1K w - - 0 1',
  solutionMove: { from: 'f1', to: 'f8' },
  rewardText: 'Gotcha! Wild Roselia was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook to f8 — the King is trapped behind its own Pawns!',
};
