// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_corsola_1_23',
  pokemonName: 'Corsola',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/222.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Corsola\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Corsola appeared in Sootopolis Lake! Slide your Rook all the way down to f8 for Checkmate!',
  fen: '2k5/1ppp4/8/8/8/8/8/5R1K w - - 0 1',
  solutionMove: { from: 'f1', to: 'f8' },
  rewardText: 'Gotcha! Wild Corsola was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to f8 — the King is trapped behind its own Pawns!',
};
