// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_torkoal_7',
  pokemonName: 'Torkoal',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/324.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Torkoal\'s Solid Pawn Push! 🌋',
  prompt: 'A Wild Torkoal appeared in Mt. Chimney Volcano! Push your Pawn to e3 — a safe, solid start!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e3' },
  rewardText: 'Gotcha! Wild Torkoal was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e3!',
};
