// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_scyther_9',
  pokemonName: 'Scyther',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Scyther\'s Free Pawn Capture! 🌿',
  prompt: 'A Wild Scyther appeared in Petalburg Woods! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/2P5/8/8/K7 w - - 0 1',
  solutionMove: { from: 'c4', to: 'd5' },
  rewardText: 'Gotcha! Wild Scyther was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from c4 to d5 to grab the Pawn!',
};
