// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_mudkip_10',
  pokemonName: 'Mudkip',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Mudkip\'s Free Pawn Capture! 💧',
  prompt: 'A Wild Mudkip appeared in Sootopolis Lake! Capture the Pawn on e5 with your Pawn!',
  fen: '7k/8/8/4p3/5P2/8/8/K7 w - - 0 1',
  solutionMove: { from: 'f4', to: 'e5' },
  rewardText: 'Gotcha! Wild Mudkip was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from f4 to e5 to grab the Pawn!',
};
