// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_mareep_9',
  pokemonName: 'Mareep',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/179.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Mareep\'s Free Pawn Capture! ⚡',
  prompt: 'A Wild Mareep appeared in Mauville Plant! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/2P5/8/8/K7 w - - 0 1',
  solutionMove: { from: 'c4', to: 'd5' },
  rewardText: 'Gotcha! Wild Mareep was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from c4 to d5 to grab the Pawn!',
};
