// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_oddish_1_29',
  pokemonName: 'Oddish',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Oddish\'s Queen Corner Checkmate! 🌿',
  prompt: 'A Wild Oddish appeared in Petalburg Woods! Bring your Queen to e8 for Checkmate — your King has already cut off the escape!',
  fen: '7k/8/6K1/8/8/8/8/4Q3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Oddish was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Queen to e8. Your King blocks two escape squares, and your Queen covers the rest!',
};
