// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_magneton_1_17',
  pokemonName: 'Magneton',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Magneton\'s Rook Swoop! ⚡',
  prompt: 'A Wild Magneton appeared in Mauville Plant! Capture the Pawn on h6 with your Rook!',
  fen: 'k7/8/7p/8/8/8/8/K6R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h6' },
  rewardText: 'Gotcha! Wild Magneton was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook from h1 to h6 to grab the Pawn!',
};
