// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_marill_6',
  pokemonName: 'Marill',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/183.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Marill\'s Fianchetto Setup! 💧',
  prompt: 'A Wild Marill appeared in Sootopolis Lake! Push your Pawn to b3 to open a path for your other Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b2', to: 'b3' },
  rewardText: 'Gotcha! Wild Marill was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from b2 to b3!',
};
