// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_piloswine_1_20',
  pokemonName: 'Piloswine',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/221.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Piloswine\'s Queen Strike! ❄️',
  prompt: 'A Wild Piloswine appeared in Shoal Ice Cave! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Piloswine was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
