// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_skarmory_3_40',
  pokemonName: 'Skarmory',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Skarmory\'s Mate in Two! ⚡',
  prompt: 'A Wild Skarmory appeared in Mauville Plant! Checkmate in 2! First, jump your Knight to c2 for check.',
  fen: '8/8/8/8/1N6/1K6/7R/k7 w - - 0 1',
  solutionMoves: [{ from: 'b4', to: 'c2' }, { from: 'a1', to: 'b1' }, { from: 'h2', to: 'h1' }],
  stepHints: ['Pikachu says: Jump your Knight to c2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to h1 for Checkmate!'],
  rewardText: 'Gotcha! Wild Skarmory was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Jump your Knight to c2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
