// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_elekid_2_27',
  pokemonName: 'Elekid',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/239.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Elekid\'s Back-Rank Checkmate! ⚡',
  prompt: 'A Wild Elekid appeared in Mauville Plant! Slide your Rook all the way down to b8 for Checkmate!',
  fen: '6k1/5ppp/8/8/8/8/8/1R1K4 w - - 0 1',
  solutionMove: { from: 'b1', to: 'b8' },
  rewardText: 'Gotcha! Wild Elekid was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook to b8 — the King is trapped behind its own Pawns!',
};
