// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_houndour_3_41',
  pokemonName: 'Houndour',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/228.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Houndour\'s Mate in Two! 🌋',
  prompt: 'A Wild Houndour appeared in Mt. Chimney Volcano! Checkmate in 2! First, jump your Knight to f2 for check.',
  fen: '8/8/8/8/6N1/6K1/R7/7k w - - 0 1',
  solutionMoves: [{ from: 'g4', to: 'f2' }, { from: 'h1', to: 'g1' }, { from: 'a2', to: 'a1' }],
  stepHints: ['Pikachu says: Jump your Knight to f2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to a1 for Checkmate!'],
  rewardText: 'Gotcha! Wild Houndour was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Jump your Knight to f2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
