// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_flaaffy_2_32',
  pokemonName: 'Flaaffy',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/180.png',
  type: 'Knight Fork',
  difficulty: 'medium',
  weight: 26,
  title: 'Flaaffy\'s Knight Fork! ⚡',
  prompt: 'A Wild Flaaffy appeared in Mauville Plant! Fork the King and the Rook — jump your Knight to e7!',
  fen: '2r3k1/5ppp/2N5/8/8/8/8/6K1 w - - 0 1',
  solutionMoves: [{ from: 'c6', to: 'e7' }, { from: 'g8', to: 'f8' }, { from: 'e7', to: 'c8' }],
  stepHints: ['Pikachu says: Jump your Knight to e7 — check! It also attacks the Rook on c8!', 'Pikachu says: The King had to run. Now capture the Rook with your Knight on c8!'],
  rewardText: 'Gotcha! Wild Flaaffy was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Jump your Knight to e7 — check! It also attacks the Rook on c8!',
};
