// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_hoppip_12',
  pokemonName: 'Hoppip',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/187.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Hoppip\'s Knight Snack! 🌿',
  prompt: 'A Wild Hoppip appeared in Petalburg Woods! Capture the Pawn on c6 with your Knight!',
  fen: '7k/8/2p5/4N3/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'e5', to: 'c6' },
  rewardText: 'Gotcha! Wild Hoppip was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from e5 to c6 to grab the Pawn!',
};
