// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_vulpix_1_12',
  pokemonName: 'Vulpix',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Vulpix\'s Knight Snack! 🌋',
  prompt: 'A Wild Vulpix appeared in Mt. Chimney Volcano! Capture the Pawn on c6 with your Knight!',
  fen: '7k/8/2p5/4N3/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'e5', to: 'c6' },
  rewardText: 'Gotcha! Wild Vulpix was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from e5 to c6 to grab the Pawn!',
};
