// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_pichu_2_26',
  pokemonName: 'Pichu',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/172.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Pichu\'s Back-Rank Checkmate! ⚡',
  prompt: 'A Wild Pichu appeared in Mauville Plant! Slide your Rook all the way down to a8 for Checkmate!',
  fen: '5k2/4ppp1/8/8/8/8/8/R1K5 w - - 0 1',
  solutionMove: { from: 'a1', to: 'a8' },
  rewardText: 'Gotcha! Wild Pichu was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook to a8 — the King is trapped behind its own Pawns!',
};
