// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_vulpix_2_24',
  pokemonName: 'Vulpix',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Vulpix\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Vulpix appeared in Mt. Chimney Volcano! Slide your Rook all the way down to g8 for Checkmate!',
  fen: '3k4/2ppp3/8/8/8/8/8/K5R1 w - - 0 1',
  solutionMove: { from: 'g1', to: 'g8' },
  rewardText: 'Gotcha! Wild Vulpix was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to g8 — the King is trapped behind its own Pawns!',
};
