// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_glalie_9',
  pokemonName: 'Glalie',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/362.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Glalie\'s Free Pawn Capture! ❄️',
  prompt: 'A Wild Glalie appeared in Shoal Ice Cave! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/2P5/8/8/K7 w - - 0 1',
  solutionMove: { from: 'c4', to: 'd5' },
  rewardText: 'Gotcha! Wild Glalie was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from c4 to d5 to grab the Pawn!',
};
