// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_growlithe_2_25',
  pokemonName: 'Growlithe',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Growlithe\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Growlithe appeared in Mt. Chimney Volcano! Slide your Rook all the way down to h8 for Checkmate!',
  fen: '4k3/3ppp2/8/8/8/8/8/1K5R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h8' },
  rewardText: 'Gotcha! Wild Growlithe was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to h8 — the King is trapped behind its own Pawns!',
};
