// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_ditto_12',
  pokemonName: 'Ditto',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Ditto\'s Knight Snack! ⭐',
  prompt: 'A Wild Ditto appeared in Indigo League! Capture the Pawn on c6 with your Knight!',
  fen: '7k/8/2p5/4N3/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'e5', to: 'c6' },
  rewardText: 'Gotcha! Wild Ditto was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from e5 to c6 to grab the Pawn!',
};
