// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_smoochum_3_40',
  pokemonName: 'Smoochum',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/238.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Smoochum\'s Mate in Two! ❄️',
  prompt: 'A Wild Smoochum appeared in Shoal Ice Cave! Checkmate in 2! First, jump your Knight to c2 for check.',
  fen: '8/8/8/8/1N6/1K6/7R/k7 w - - 0 1',
  solutionMoves: [{ from: 'b4', to: 'c2' }, { from: 'a1', to: 'b1' }, { from: 'h2', to: 'h1' }],
  stepHints: ['Pikachu says: Jump your Knight to c2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to h1 for Checkmate!'],
  rewardText: 'Gotcha! Wild Smoochum was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Jump your Knight to c2 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
