// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_skarmory_7',
  pokemonName: 'Skarmory',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Skarmory\'s Solid Pawn Push! ⚡',
  prompt: 'A Wild Skarmory appeared in Mauville Plant! Push your Pawn to e3 — a safe, solid start!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e3' },
  rewardText: 'Gotcha! Wild Skarmory was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e3!',
};
