// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_meowth_1_20',
  pokemonName: 'Meowth',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Meowth\'s Queen Strike! ⭐',
  prompt: 'A Wild Meowth appeared in Indigo League! Capture the Bishop on d5 with your Queen!',
  fen: '7k/8/8/3b4/8/8/8/K2Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd5' },
  rewardText: 'Gotcha! Wild Meowth was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Queen from d1 to d5 to grab the Bishop!',
};
