// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_delibird_3',
  pokemonName: 'Delibird',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Delibird\'s Knight Development! ❄️',
  prompt: 'A Wild Delibird appeared in Shoal Ice Cave! Develop your Knight to c3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b1', to: 'c3' },
  rewardText: 'Gotcha! Wild Delibird was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Knight from b1 to c3!',
};
