// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_qwilfish_9',
  pokemonName: 'Qwilfish',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/211.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Qwilfish\'s Free Pawn Capture! 💧',
  prompt: 'A Wild Qwilfish appeared in Sootopolis Lake! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/2P5/8/8/K7 w - - 0 1',
  solutionMove: { from: 'c4', to: 'd5' },
  rewardText: 'Gotcha! Wild Qwilfish was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from c4 to d5 to grab the Pawn!',
};
