// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_electrike_1_12',
  pokemonName: 'Electrike',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/309.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Electrike\'s Knight Snack! ⚡',
  prompt: 'A Wild Electrike appeared in Mauville Plant! Capture the Pawn on c6 with your Knight!',
  fen: '7k/8/2p5/4N3/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'e5', to: 'c6' },
  rewardText: 'Gotcha! Wild Electrike was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Knight from e5 to c6 to grab the Pawn!',
};
