// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_chinchou_1_24',
  pokemonName: 'Chinchou',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/170.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Chinchou\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Chinchou appeared in Sootopolis Lake! Slide your Rook all the way down to g8 for Checkmate!',
  fen: '3k4/2ppp3/8/8/8/8/8/K5R1 w - - 0 1',
  solutionMove: { from: 'g1', to: 'g8' },
  rewardText: 'Gotcha! Wild Chinchou was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to g8 — the King is trapped behind its own Pawns!',
};
