// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_camerupt_11',
  pokemonName: 'Camerupt',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/323.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Camerupt\'s Knight Snack! 🌋',
  prompt: 'A Wild Camerupt appeared in Mt. Chimney Volcano! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Camerupt was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
