// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_dewgong_1_17',
  pokemonName: 'Dewgong',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Dewgong\'s Rook Swoop! ❄️',
  prompt: 'A Wild Dewgong appeared in Shoal Ice Cave! Capture the Pawn on h6 with your Rook!',
  fen: 'k7/8/7p/8/8/8/8/K6R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h6' },
  rewardText: 'Gotcha! Wild Dewgong was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook from h1 to h6 to grab the Pawn!',
};
