// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_carvanha_12',
  pokemonName: 'Carvanha',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/318.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Carvanha\'s Knight Snack! 💧',
  prompt: 'A Wild Carvanha appeared in Sootopolis Lake! Capture the Pawn on c6 with your Knight!',
  fen: '7k/8/2p5/4N3/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'e5', to: 'c6' },
  rewardText: 'Gotcha! Wild Carvanha was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Knight from e5 to c6 to grab the Pawn!',
};
