// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_seedot_17',
  pokemonName: 'Seedot',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/273.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Seedot\'s Rook Swoop! 🌿',
  prompt: 'A Wild Seedot appeared in Petalburg Woods! Capture the Pawn on h6 with your Rook!',
  fen: 'k7/8/7p/8/8/8/8/K6R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h6' },
  rewardText: 'Gotcha! Wild Seedot was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Rook from h1 to h6 to grab the Pawn!',
};
