// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_scyther_1_33',
  pokemonName: 'Scyther',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
  type: 'Knight Fork',
  difficulty: 'hard',
  weight: 16,
  title: 'Scyther\'s Knight Fork! 🌿',
  prompt: 'A Wild Scyther appeared in Petalburg Woods! Fork the King and the Queen — jump your Knight to e7!',
  fen: '2q3k1/5ppp/2N5/8/8/8/8/6K1 w - - 0 1',
  solutionMoves: [{ from: 'c6', to: 'e7' }, { from: 'g8', to: 'f8' }, { from: 'e7', to: 'c8' }],
  stepHints: ['Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!', 'Pikachu says: The King had to run. Now capture the Queen with your Knight on c8!'],
  rewardText: 'Gotcha! Wild Scyther was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!',
};
