// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_houndour_1_17',
  pokemonName: 'Houndour',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/228.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Houndour\'s Rook Swoop! 🌋',
  prompt: 'A Wild Houndour appeared in Mt. Chimney Volcano! Capture the Pawn on h6 with your Rook!',
  fen: 'k7/8/7p/8/8/8/8/K6R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h6' },
  rewardText: 'Gotcha! Wild Houndour was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook from h1 to h6 to grab the Pawn!',
};
