// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_torchic_2_33',
  pokemonName: 'Torchic',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png',
  type: 'Knight Fork',
  difficulty: 'hard',
  weight: 16,
  title: 'Torchic\'s Knight Fork! 🌋',
  prompt: 'A Wild Torchic appeared in Mt. Chimney Volcano! Fork the King and the Queen — jump your Knight to e7!',
  fen: '2q3k1/5ppp/2N5/8/8/8/8/6K1 w - - 0 1',
  solutionMoves: [{ from: 'c6', to: 'e7' }, { from: 'g8', to: 'f8' }, { from: 'e7', to: 'c8' }],
  stepHints: ['Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!', 'Pikachu says: The King had to run. Now capture the Queen with your Knight on c8!'],
  rewardText: 'Gotcha! Wild Torchic was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Jump your Knight to e7 — check! It also attacks the Queen on c8!',
};
