// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_torkoal_2_31',
  pokemonName: 'Torkoal',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/324.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Torkoal\'s Queen Corner Checkmate! 🌋',
  prompt: 'A Wild Torkoal appeared in Mt. Chimney Volcano! Bring your Queen to e1 for Checkmate — your King has already cut off the escape!',
  fen: '4Q3/8/8/8/8/6K1/8/7k w - - 0 1',
  solutionMove: { from: 'e8', to: 'e1' },
  rewardText: 'Gotcha! Wild Torkoal was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Queen to e1. Your King blocks two escape squares, and your Queen covers the rest!',
};
