// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_voltorb_1_11',
  pokemonName: 'Voltorb',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Voltorb\'s Knight Snack! ⚡',
  prompt: 'A Wild Voltorb appeared in Mauville Plant! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Voltorb was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
