// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_clamperl_15',
  pokemonName: 'Clamperl',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/366.png',
  type: 'Bishop Dive',
  difficulty: 'medium',
  weight: 30,
  title: 'Clamperl\'s Bishop Dive! 💧',
  prompt: 'A Wild Clamperl appeared in Sootopolis Lake! Capture the Pawn on f7 with your Bishop!',
  fen: 'k7/5p2/8/8/2B5/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'c4', to: 'f7' },
  rewardText: 'Gotcha! Wild Clamperl was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Bishop from c4 to f7 to grab the Pawn!',
};
