// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_wurmple_14',
  pokemonName: 'Wurmple',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/265.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 30,
  title: 'Wurmple\'s Knight Snack! 🌿',
  prompt: 'A Wild Wurmple appeared in Petalburg Woods! Capture the Bishop on d6 with your Knight!',
  fen: '7k/8/3b4/5N2/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'f5', to: 'd6' },
  rewardText: 'Gotcha! Wild Wurmple was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from f5 to d6 to grab the Bishop!',
};
