// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_bellsprout_8',
  pokemonName: 'Bellsprout',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
  type: 'Free Pawn Capture',
  difficulty: 'easy',
  weight: 55,
  title: 'Bellsprout\'s Free Pawn Capture! 🌿',
  prompt: 'A Wild Bellsprout appeared in Petalburg Woods! Capture the Pawn on d5 with your Pawn!',
  fen: '7k/8/8/3p4/4P3/8/8/K7 w - - 0 1',
  solutionMove: { from: 'e4', to: 'd5' },
  rewardText: 'Gotcha! Wild Bellsprout was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from e4 to d5 to grab the Pawn!',
};
