// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_sneasel_1_14',
  pokemonName: 'Sneasel',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 30,
  title: 'Sneasel\'s Knight Snack! ❄️',
  prompt: 'A Wild Sneasel appeared in Shoal Ice Cave! Capture the Bishop on d6 with your Knight!',
  fen: '7k/8/3b4/5N2/8/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'f5', to: 'd6' },
  rewardText: 'Gotcha! Wild Sneasel was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Knight from f5 to d6 to grab the Bishop!',
};
