// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_venonat_1_31',
  pokemonName: 'Venonat',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Venonat\'s Queen Corner Checkmate! 🌿',
  prompt: 'A Wild Venonat appeared in Petalburg Woods! Bring your Queen to e1 for Checkmate — your King has already cut off the escape!',
  fen: '4Q3/8/8/8/8/6K1/8/7k w - - 0 1',
  solutionMove: { from: 'e8', to: 'e1' },
  rewardText: 'Gotcha! Wild Venonat was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Queen to e1. Your King blocks two escape squares, and your Queen covers the rest!',
};
