// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_machop_1_22',
  pokemonName: 'Machop',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Machop\'s Back-Rank Checkmate! ⭐',
  prompt: 'A Wild Machop appeared in Indigo League! Slide your Rook all the way down to e8 for Checkmate!',
  fen: '1k6/ppp5/8/8/8/8/8/4R1K1 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Machop was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Rook to e8 — the King is trapped behind its own Pawns!',
};
