// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_qwilfish_1_25',
  pokemonName: 'Qwilfish',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/211.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Qwilfish\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Qwilfish appeared in Sootopolis Lake! Slide your Rook all the way down to h8 for Checkmate!',
  fen: '4k3/3ppp2/8/8/8/8/8/1K5R w - - 0 1',
  solutionMove: { from: 'h1', to: 'h8' },
  rewardText: 'Gotcha! Wild Qwilfish was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to h8 — the King is trapped behind its own Pawns!',
};
