// Auto-generated by scripts/generate-wild-puzzles.mjs — Mt. Chimney Volcano (volcano)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_volcano_ponyta_2_26',
  pokemonName: 'Ponyta',
  region: 'volcano',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Ponyta\'s Back-Rank Checkmate! 🌋',
  prompt: 'A Wild Ponyta appeared in Mt. Chimney Volcano! Slide your Rook all the way down to a8 for Checkmate!',
  fen: '5k2/4ppp1/8/8/8/8/8/R1K5 w - - 0 1',
  solutionMove: { from: 'a1', to: 'a8' },
  rewardText: 'Gotcha! Wild Ponyta was caught! Registered in Mt. Chimney Volcano Pokedex! 🌋',
  coachHint: 'Pikachu says: Move your Rook to a8 — the King is trapped behind its own Pawns!',
};
