// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_swinub_1_13',
  pokemonName: 'Swinub',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Swinub\'s Knight Snack! ❄️',
  prompt: 'A Wild Swinub appeared in Shoal Ice Cave! Capture the Pawn on d5 with your Knight!',
  fen: '7k/8/8/3p4/8/2N5/8/6K1 w - - 0 1',
  solutionMove: { from: 'c3', to: 'd5' },
  rewardText: 'Gotcha! Wild Swinub was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Knight from c3 to d5 to grab the Pawn!',
};
