// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_caterpie_0',
  pokemonName: 'Caterpie',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Caterpie\'s King Pawn Push! 🌿',
  prompt: 'A Wild Caterpie appeared in Petalburg Woods! Advance your Pawn to e4 to control the center!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e4' },
  rewardText: 'Gotcha! Wild Caterpie was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e4!',
};
