// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_delibird_1_15',
  pokemonName: 'Delibird',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png',
  type: 'Bishop Dive',
  difficulty: 'medium',
  weight: 30,
  title: 'Delibird\'s Bishop Dive! ❄️',
  prompt: 'A Wild Delibird appeared in Shoal Ice Cave! Capture the Pawn on f7 with your Bishop!',
  fen: 'k7/5p2/8/8/2B5/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'c4', to: 'f7' },
  rewardText: 'Gotcha! Wild Delibird was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Bishop from c4 to f7 to grab the Pawn!',
};
