// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_wooper_5',
  pokemonName: 'Wooper',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/194.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Wooper\'s Fianchetto Setup! 💧',
  prompt: 'A Wild Wooper appeared in Sootopolis Lake! Push your Pawn to g3 to open a path for your Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g2', to: 'g3' },
  rewardText: 'Gotcha! Wild Wooper was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from g2 to g3!',
};
