// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_magneton_2_28',
  pokemonName: 'Magneton',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Magneton\'s Queen Corner Checkmate! ⚡',
  prompt: 'A Wild Magneton appeared in Mauville Plant! Bring your Queen to d8 for Checkmate — your King has already cut off the escape!',
  fen: 'k7/8/1K6/8/8/8/8/3Q4 w - - 0 1',
  solutionMove: { from: 'd1', to: 'd8' },
  rewardText: 'Gotcha! Wild Magneton was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Queen to d8. Your King blocks two escape squares, and your Queen covers the rest!',
};
