// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_seel_1_18',
  pokemonName: 'Seel',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Seel\'s Rook Swoop! ❄️',
  prompt: 'A Wild Seel appeared in Shoal Ice Cave! Capture the Knight on a6 with your Rook!',
  fen: '7k/8/n7/8/8/8/8/R6K w - - 0 1',
  solutionMove: { from: 'a1', to: 'a6' },
  rewardText: 'Gotcha! Wild Seel was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook from a1 to a6 to grab the Knight!',
};
