// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_magikarp_7',
  pokemonName: 'Magikarp',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Magikarp\'s Solid Pawn Push! ⭐',
  prompt: 'A Wild Magikarp appeared in Indigo League! Push your Pawn to e3 — a safe, solid start!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e3' },
  rewardText: 'Gotcha! Wild Magikarp was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e3!',
};
