// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_spearow_16',
  pokemonName: 'Spearow',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
  type: 'Long Diagonal Snipe',
  difficulty: 'medium',
  weight: 30,
  title: 'Spearow\'s Long Diagonal Snipe! ⭐',
  prompt: 'A Wild Spearow appeared in Indigo League! Capture the Pawn on b7 with your Bishop!',
  fen: '7k/1p6/8/8/8/8/6B1/K7 w - - 0 1',
  solutionMove: { from: 'g2', to: 'b7' },
  rewardText: 'Gotcha! Wild Spearow was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Bishop from g2 to b7 to grab the Pawn!',
};
