// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_staryu_4',
  pokemonName: 'Staryu',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Staryu\'s Wing Pawn Push! 💧',
  prompt: 'A Wild Staryu appeared in Sootopolis Lake! Advance your Pawn to c4 for extra space!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'c2', to: 'c4' },
  rewardText: 'Gotcha! Wild Staryu was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from c2 to c4!',
};
