// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_sunkern_11',
  pokemonName: 'Sunkern',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/191.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Sunkern\'s Knight Snack! 🌿',
  prompt: 'A Wild Sunkern appeared in Petalburg Woods! Capture the Pawn on b5 with your Knight!',
  fen: '7k/8/8/1p6/3N4/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'd4', to: 'b5' },
  rewardText: 'Gotcha! Wild Sunkern was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Knight from d4 to b5 to grab the Pawn!',
};
