// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_metapod_1',
  pokemonName: 'Metapod',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Metapod\'s Queen Pawn Push! 🌿',
  prompt: 'A Wild Metapod appeared in Petalburg Woods! Push your Queen Pawn to d4 to claim the middle!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'd2', to: 'd4' },
  rewardText: 'Gotcha! Wild Metapod was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from d2 to d4!',
};
