// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_jynx_2_31',
  pokemonName: 'Jynx',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Jynx\'s Queen Corner Checkmate! ❄️',
  prompt: 'A Wild Jynx appeared in Shoal Ice Cave! Bring your Queen to e1 for Checkmate — your King has already cut off the escape!',
  fen: '4Q3/8/8/8/8/6K1/8/7k w - - 0 1',
  solutionMove: { from: 'e8', to: 'e1' },
  rewardText: 'Gotcha! Wild Jynx was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Queen to e1. Your King blocks two escape squares, and your Queen covers the rest!',
};
