// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_seel_6',
  pokemonName: 'Seel',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Seel\'s Fianchetto Setup! ❄️',
  prompt: 'A Wild Seel appeared in Shoal Ice Cave! Push your Pawn to b3 to open a path for your other Bishop!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'b2', to: 'b3' },
  rewardText: 'Gotcha! Wild Seel was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Pawn from b2 to b3!',
};
