// Auto-generated by scripts/generate-wild-puzzles.mjs — Petalburg Woods (petalburg)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_petalburg_beedrill_4',
  pokemonName: 'Beedrill',
  region: 'petalburg',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Beedrill\'s Wing Pawn Push! 🌿',
  prompt: 'A Wild Beedrill appeared in Petalburg Woods! Advance your Pawn to c4 for extra space!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'c2', to: 'c4' },
  rewardText: 'Gotcha! Wild Beedrill was caught! Registered in Petalburg Woods Pokedex! 🌿',
  coachHint: 'Pikachu says: Move your Pawn from c2 to c4!',
};
