// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_pidgeotto_15',
  pokemonName: 'Pidgeotto',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
  type: 'Bishop Dive',
  difficulty: 'medium',
  weight: 30,
  title: 'Pidgeotto\'s Bishop Dive! ⭐',
  prompt: 'A Wild Pidgeotto appeared in Indigo League! Capture the Pawn on f7 with your Bishop!',
  fen: 'k7/5p2/8/8/2B5/8/8/6K1 w - - 0 1',
  solutionMove: { from: 'c4', to: 'f7' },
  rewardText: 'Gotcha! Wild Pidgeotto was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Bishop from c4 to f7 to grab the Pawn!',
};
