// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_snorlax_13',
  pokemonName: 'Snorlax',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
  type: 'Knight Snack',
  difficulty: 'medium',
  weight: 35,
  title: 'Snorlax\'s Knight Snack! ⭐',
  prompt: 'A Wild Snorlax appeared in Indigo League! Capture the Pawn on d5 with your Knight!',
  fen: '7k/8/8/3p4/8/2N5/8/6K1 w - - 0 1',
  solutionMove: { from: 'c3', to: 'd5' },
  rewardText: 'Gotcha! Wild Snorlax was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from c3 to d5 to grab the Pawn!',
};
