// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_tentacool_1',
  pokemonName: 'Tentacool',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Tentacool\'s Queen Pawn Push! 💧',
  prompt: 'A Wild Tentacool appeared in Sootopolis Lake! Push your Queen Pawn to d4 to claim the middle!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'd2', to: 'd4' },
  rewardText: 'Gotcha! Wild Tentacool was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Pawn from d2 to d4!',
};
