// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_voltorb_0',
  pokemonName: 'Voltorb',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Voltorb\'s King Pawn Push! ⚡',
  prompt: 'A Wild Voltorb appeared in Mauville Plant! Advance your Pawn to e4 to control the center!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'e2', to: 'e4' },
  rewardText: 'Gotcha! Wild Voltorb was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Pawn from e2 to e4!',
};
