// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_meowth_2_38',
  pokemonName: 'Meowth',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
  type: 'Mate in Two',
  difficulty: 'hard',
  weight: 12,
  title: 'Meowth\'s Mate in Two! ⭐',
  prompt: 'A Wild Meowth appeared in Indigo League! Checkmate in 2! First, jump your Knight to c7 for check.',
  fen: 'k7/7R/1K6/1N6/8/8/8/8 w - - 0 1',
  solutionMoves: [{ from: 'b5', to: 'c7' }, { from: 'a8', to: 'b8' }, { from: 'h7', to: 'h8' }],
  stepHints: ['Pikachu says: Jump your Knight to c7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.', 'Pikachu says: Now bring your Rook all the way to h8 for Checkmate!'],
  rewardText: 'Gotcha! Wild Meowth was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Jump your Knight to c7 — check! Your King already blocks two escape squares, so there\'s only one square left for the enemy King to run to.',
};
