// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_meowth_2',
  pokemonName: 'Meowth',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
  type: 'Opening',
  difficulty: 'easy',
  weight: 60,
  title: 'Meowth\'s Knight Development! ⭐',
  prompt: 'A Wild Meowth appeared in Indigo League! Develop your Knight to f3!',
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  solutionMove: { from: 'g1', to: 'f3' },
  rewardText: 'Gotcha! Wild Meowth was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Knight from g1 to f3!',
};
