// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_flaaffy_1_21',
  pokemonName: 'Flaaffy',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/180.png',
  type: 'Queen Strike',
  difficulty: 'hard',
  weight: 18,
  title: 'Flaaffy\'s Queen Strike! ⚡',
  prompt: 'A Wild Flaaffy appeared in Mauville Plant! Capture the Rook on d7 with your Queen!',
  fen: '7k/3r4/8/8/Q7/8/8/K7 w - - 0 1',
  solutionMove: { from: 'a4', to: 'd7' },
  rewardText: 'Gotcha! Wild Flaaffy was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Queen from a4 to d7 to grab the Rook!',
};
