// Auto-generated by scripts/generate-wild-puzzles.mjs — Sootopolis Lake (sootopolis)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_sootopolis_marill_1_22',
  pokemonName: 'Marill',
  region: 'sootopolis',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/183.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Marill\'s Back-Rank Checkmate! 💧',
  prompt: 'A Wild Marill appeared in Sootopolis Lake! Slide your Rook all the way down to e8 for Checkmate!',
  fen: '1k6/ppp5/8/8/8/8/8/4R1K1 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Marill was caught! Registered in Sootopolis Lake Pokedex! 💧',
  coachHint: 'Pikachu says: Move your Rook to e8 — the King is trapped behind its own Pawns!',
};
