// Auto-generated by scripts/generate-wild-puzzles.mjs — Mauville Plant (mauville)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_mauville_voltorb_2_22',
  pokemonName: 'Voltorb',
  region: 'mauville',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
  type: 'Back-Rank Checkmate',
  difficulty: 'medium',
  weight: 22,
  title: 'Voltorb\'s Back-Rank Checkmate! ⚡',
  prompt: 'A Wild Voltorb appeared in Mauville Plant! Slide your Rook all the way down to e8 for Checkmate!',
  fen: '1k6/ppp5/8/8/8/8/8/4R1K1 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e8' },
  rewardText: 'Gotcha! Wild Voltorb was caught! Registered in Mauville Plant Pokedex! ⚡',
  coachHint: 'Pikachu says: Move your Rook to e8 — the King is trapped behind its own Pawns!',
};
