// Auto-generated by scripts/generate-wild-puzzles.mjs — Shoal Ice Cave (ice)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_ice_jynx_1_19',
  pokemonName: 'Jynx',
  region: 'ice',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
  type: 'Rook Swoop',
  difficulty: 'medium',
  weight: 25,
  title: 'Jynx\'s Rook Swoop! ❄️',
  prompt: 'A Wild Jynx appeared in Shoal Ice Cave! Capture the Knight on e6 with your Rook!',
  fen: '7k/8/4n3/8/8/8/8/K3R3 w - - 0 1',
  solutionMove: { from: 'e1', to: 'e6' },
  rewardText: 'Gotcha! Wild Jynx was caught! Registered in Shoal Ice Cave Pokedex! ❄️',
  coachHint: 'Pikachu says: Move your Rook from e1 to e6 to grab the Knight!',
};
