// Auto-generated by scripts/generate-wild-puzzles.mjs — Indigo League (classic)
// Do not hand-edit shape/geometry fields (fen, solutionMove(s)) without re-running
// `npm run audit:puzzles`.
export default {
  id: 'wild_classic_snorlax_1_31',
  pokemonName: 'Snorlax',
  region: 'classic',
  iconUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
  type: 'Queen Corner Checkmate',
  difficulty: 'hard',
  weight: 15,
  title: 'Snorlax\'s Queen Corner Checkmate! ⭐',
  prompt: 'A Wild Snorlax appeared in Indigo League! Bring your Queen to e1 for Checkmate — your King has already cut off the escape!',
  fen: '4Q3/8/8/8/8/6K1/8/7k w - - 0 1',
  solutionMove: { from: 'e8', to: 'e1' },
  rewardText: 'Gotcha! Wild Snorlax was caught! Registered in Indigo League Pokedex! ⭐',
  coachHint: 'Pikachu says: Move your Queen to e1. Your King blocks two escape squares, and your Queen covers the rest!',
};
